### PR TITLE
fix rstick option so it works remove input interface as its not needed

### PR DESCRIPTION
**Pull request by grant2258**

### CODE REVIEW

**Comment by grant2258** [comment]
this rstick option was re implemented for people with snes pads incase you are wondering why its back. Its in its propper place now though. So you can use the rstick or buttons

**Comment by markwkidd** [comment]
Pardon me I have edited your title - I see that you are still planning to do a test so I didn't want one of us to accidentally merge the PR prematurely

**Comment by grant2258** [comment]
No the test is something different is ok to pull this. It will have no effect on the test

**Comment by grant2258** [comment]
I'm pretty sure the the other option just delete the config and puts a map in

**Comment by markwkidd** [comment]
got it, thanks and merged

**Pull request merged**
