### PR TITLE
WIP: Attempt to hook up the sound mcu for Ghox

### PR DESCRIPTION
**Pull request by arcadez**
Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by arcadez** [comment]
Im not sure if this will work long story short the code is fine and Ghox is playable in my
MAME84 xbox core, however in my MAME72 test core it booted to a black screen and
was not fuctional.

It might be the Z180 CPU is not correct in the older cores to handle the mcu commands.??
anyway please try it out guys just drop this mcu rom into your ghox rom zip folder and
lemmie know either way.

https://www.sendspace.com/file/1hngsg

**Comment by grant2258** [comment]
@arcadez can you send a pull req for this too https://github.com/grant2258/mame2003-plus-libretro ill test it out if its not working ill try look into it more

**Comment by grant2258** [comment]
I am indeed getting the black screen give me a few days before abandoning this ill see if i can find anything mr arcadez.

**Comment by arcadez** [comment]
Thanks for testing it out i'll focus on the Z180 i've already backported some opcode changes
from the 84 version but no dice i'll need to look at what changed for the big memory rewrite
in MAME79.

**Comment by arcadez** [comment]
Dont merge for now

**Comment by arcadez** [comment]
Hmmm i see no other diffs apart from the previously mentioned opcode changes but
there was some new IRQ_PRT0 code from when they added 20pacgal in M80 i added it
on spec and still Ghox wont boot this is a bummer alright.

**Comment by grant2258** [comment]
i looked throught the z180 changes form mame 084 nothing has changed accept the cpu interface code so i dont think its anything to do with the z180 per say is indeed a strange one

**Comment by arcadez** [comment]
Ya win some lose some

**Pull request closed without merging**
