### PR TITLE
fix sample loading & simplify path selection

### PR DESCRIPTION
**Pull request by markwkidd**
Well, this is what got me started down the rabbit hole. This should get samples loading from within the system folder as intended.

### CODE REVIEW

**Comment by markwkidd** [comment]
fixed in https://github.com/libretro/mame2003-plus-libretro/pull/84

**Comment by grant2258** [comment]
ah sorry mate must have been pretty recent i just done a grep appoligies

**Comment by markwkidd** [comment]
No I did that PR after you pointed it out. I'm seeing things because I credited it to arcadez but it should have been you

**Comment by grant2258** [comment]
credits dont matter you done the work take a few days off mate! Ill fix the timing up to my new way and test it on mame2003 plus if we get no complaints ill run it by dank he seemed happy with what i showed him before

**Pull request merged**
