### PR TITLE
backport Alien Arena - alienar

### PR DESCRIPTION
**Pull request by markwkidd**
I thought it might be possible and interesting to try to backport Alien Arena from MAME 0.104u5 since it didn't seem like anything too complicated had changed.

That being said, it's crashing with an unhelpful segmentation fault. Does anyone have any advice or thoughts?

### CODE REVIEW

**Comment by grant2258** [comment]
had a quick look for a start the driver_init would need the banking set for a start the newer driver uses different banking

**Comment by arcadez** [comment]
Ya didnae put the full rom in by looks................

ROM_START( alienar )
	ROM_REGION( 0x19000, REGION_CPU1, 0 )
	ROM_LOAD( "aarom10",   0x0d000, 0x1000, CRC(6feb0314) SHA1(5cf30f097bc695cbd388cb408e78394926362a7b) )
	ROM_LOAD( "aarom11",   0x0e000, 0x1000, CRC(ae3a270e) SHA1(867fff32062bc876390e8ca6bd7cedae47cd92c9) )
	ROM_LOAD( "aarom12",   0x0f000, 0x1000, CRC(6be9f09e) SHA1(98821c9b94301c5fd6e7f5d9e4bc9c1bdbab53ec) )
	ROM_LOAD( "aarom01",   0x10000, 0x1000, CRC(bb0c21be) SHA1(dbf122870adaa49cd99e2c1e9fa4b78fb74ef2c1) )
	ROM_LOAD( "aarom02",   0x11000, 0x1000, CRC(165acd37) SHA1(12466c94bcf5a98f154a639ecc2e95d5193cbab2) )
	ROM_LOAD( "aarom03",   0x12000, 0x1000, CRC(e5d51d92) SHA1(598c928499e977a30906319c97ffa1ef2b9395d1) )
	ROM_LOAD( "aarom04",   0x13000, 0x1000, CRC(24f6feb8) SHA1(c1b7d764785b4edfe80a90ffdc52a67c8dbbfea5) )
	ROM_LOAD( "aarom05",   0x14000, 0x1000, CRC(5b1ac59b) SHA1(9b312eb419e994a006fda2ae61c58c31f048bace) )
	ROM_LOAD( "aarom06",   0x15000, 0x1000, CRC(da7195a2) SHA1(ef2c2750c504176fd6a11e8463278d97cac9a5c5) )
	ROM_LOAD( "aarom07",   0x16000, 0x1000, CRC(f9812be4) SHA1(5f116345f09cd79790612672aa48ede63fc91f56) )
	ROM_LOAD( "aarom08",   0x17000, 0x1000, CRC(cd7f3a87) SHA1(59577059308931139ecc036d06953660a148d91c) )
	ROM_LOAD( "aarom09",   0x18000, 0x1000, CRC(e6ce77b4) SHA1(bd4354100067654d0ad2e590591582dbdfb845b6) )

	ROM_REGION( 0x10000, REGION_CPU2, 0 )
	ROM_LOAD( "sg.snd",    0xf800, 0x0800, CRC(2fcf6c4d) SHA1(9c4334ac3ff15d94001b22fc367af40f9deb7d57) )

	ROM_REGION( 0x0400, REGION_PROMS, 0 )
	ROM_LOAD( "decoder.4", 0x0000, 0x0200, CRC(e6631c23) SHA1(9988723269367fb44ef83f627186a1c88cf7877e) )
	ROM_LOAD( "decoder.6", 0x0200, 0x0200, CRC(83faf25e) SHA1(30002643d08ed983a6701a7c4b5ee74a2f4a1adb) )
ROM_END

**Comment by markwkidd** [comment]
That romset is a clone with a few extra ROMs on the board because its a conversion from Stargate. The original creator of the game contacted MAME right after it was added to provide a "pure" version.

@grant2258 I guess any one that works is fine because they should be functionally equivalent and run from the same source but FWIW I'm referring to this source here: https://github.com/fesh0r/old-mame/blob/81d5aca38e9273ab2df46daef530667bf6dc07b4/src/drivers/williams.c

**Comment by grant2258** [comment]
@markwkidd 

https://github.com/libretro/mame2003-plus-libretro/blob/526869ee501c379740e652c697cb7b9f34f67db8/src/drivers/williams.c#L2170-L2171 

we do banking different in our driver is what i meant

**Comment by markwkidd** [comment]
Is that a serious obstacle? This is my first time swimming in these waters. I'm looking at the more recent MAME 0.104 code and I don't see an obvious equivalent to those bank arrays.

**Comment by grant2258** [comment]
you can look at my dkong x fix here for our core the newer diver must be using different offsets from ours. 

https://github.com/libretro/mame2003-plus-libretro/pull/527/commits/235ad33894e09fd8ffa7984227e78c4ab8459bca

I think its good to learn this stuff though mark it will give you a big appreciation into the amount of work our local guru mr arcadez  put into these driver ports

**Comment by markwkidd** [comment]
I did try to look for that kind of issue but I honestly don't know for sure that I would recognize a change if I saw it. I will look again.

BTW you will notice that there is now an "Alien Arena" content download within RetroArch's GUI which will yield this romset.

**Comment by markwkidd** [comment]
@grant2258 I just pushed a buildfix to this branch that you may want to pull into yours

I'm getting a segfault and I'll try to get a backtrace

**Comment by grant2258** [comment]
this didnt merge properly jsut download the file  ill give you the link
https://github.com/grant2258/mame2003-plus-libretro/blob/alienar/src/drivers/williams.c

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/pull/537/commits/328fd8cce1628f6d6fe3f355715a92cfad03e643 this is all i changed from your code not impressed with github lol it hates me

**Comment by grant2258** [comment]
```
ROM_START( alienar )
	ROM_REGION( 0x19000, REGION_CPU1, 0 )
	ROM_LOAD( "aarom10",   0xd000, 0x1000, CRC(6feb0314) SHA1(5cf30f097bc695cbd388cb408e78394926362a7b) )
	ROM_LOAD( "aarom11",   0xe000, 0x1000, CRC(ae3a270e) SHA1(867fff32062bc876390e8ca6bd7cedae47cd92c9) )
	ROM_LOAD( "aarom12",   0xf000, 0x1000, CRC(6be9f09e) SHA1(98821c9b94301c5fd6e7f5d9e4bc9c1bdbab53ec) )
	ROM_LOAD( "aarom01",   0x0000, 0x1000, CRC(bb0c21be) SHA1(dbf122870adaa49cd99e2c1e9fa4b78fb74ef2c1) )
	ROM_LOAD( "aarom02",   0x1000, 0x1000, CRC(165acd37) SHA1(12466c94bcf5a98f154a639ecc2e95d5193cbab2) )
	ROM_LOAD( "aarom03",   0x2000, 0x1000, CRC(e5d51d92) SHA1(598c928499e977a30906319c97ffa1ef2b9395d1) )
	ROM_LOAD( "aarom04",   0x3000, 0x1000, CRC(24f6feb8) SHA1(c1b7d764785b4edfe80a90ffdc52a67c8dbbfea5) )
	ROM_LOAD( "aarom05",   0x4000, 0x1000, CRC(5b1ac59b) SHA1(9b312eb419e994a006fda2ae61c58c31f048bace) )
	ROM_LOAD( "aarom06",   0x5000, 0x1000, CRC(da7195a2) SHA1(ef2c2750c504176fd6a11e8463278d97cac9a5c5) )
	ROM_LOAD( "aarom07",   0x6000, 0x1000, CRC(f9812be4) SHA1(5f116345f09cd79790612672aa48ede63fc91f56) )
	ROM_LOAD( "aarom08",   0x7000, 0x1000, CRC(cd7f3a87) SHA1(59577059308931139ecc036d06953660a148d91c) )
	ROM_LOAD( "aarom09",   0x8000, 0x1000, CRC(e6ce77b4) SHA1(bd4354100067654d0ad2e590591582dbdfb845b6) )

	ROM_REGION( 0x10000, REGION_CPU2, 0 )
	ROM_LOAD( "sg.snd",    0xf800, 0x0800, CRC(2fcf6c4d) SHA1(9c4334ac3ff15d94001b22fc367af40f9deb7d57) )

	/*
	ROM_REGION( 0x0400, REGION_PROMS, 0 )
	ROM_LOAD( "decoder.4", 0x0000, 0x0200, CRC(e6631c23) SHA1(9988723269367fb44ef83f627186a1c88cf7877e) )
	ROM_LOAD( "decoder.6", 0x0200, 0x0200, CRC(83faf25e) SHA1(30002643d08ed983a6701a7c4b5ee74a2f4a1adb) )
	*/
	ROM_END
```
and

```
- install_mem_write_handler (0, 0xcbff, 0xcbff, MWA_NOP);
+ install_mem_read_handler (0, 0xcbff, 0xcbff, MWA_NOP);
```

**Comment by markwkidd** [comment]
I found the missing input code just before you pointed it out, I swear. But even with the missing `IN3` section @grant2258 I don't have any controls. Sorry to bug you about this, I was so premature in merging..

**Comment by grant2258** [comment]
mark i fixed this the code is updated one extra line new code is on my branch and posted on discord

**Pull request merged**
