### PR TITLE
Add games

### PR DESCRIPTION
**Pull request by MistyDreams**
Cotton gfx issue will clear up once you implent the sound how you choose

### CODE REVIEW

**Comment by mahoneyt944** [comment]
Thanks for creating this PR, some minor things need cleaned up first before a merge though, ignore this if you haven't gotten to it yet since I see you're still committing things, but just giving you a heads up if overlooked.

- Cotton should only have one machine driver, seems a bit odd to create a machine driver for cotton then import it into another one for cotton. I'm assuming we want the driver for cotton to import the regular 7759 machine driver then modify it with the cotton changes? Didn't look much into it.

- system16_update_0_proc(), we already have a type0_sys16_textram(). Should probably just update that one with your changes.

- nit picking, but spacing issues...spacebar vs tab button kind of stuff. Shows oddly in the diff.

**Comment by MistyDreams** [comment]
you type 0 differs from mine cotton has no driver neither does bullet the source formatting its a complete mess everywhere so yes it is nit picking

**Comment by MistyDreams** [comment]
i would suggest the core update any issues with the pr feel free to close it. I wont be worrying about tabs and spaces when the whole code base formatting is a mess and looking at previous prs submitted youve have no issues with bad formatting before .

**Comment by mahoneyt944** [comment]
I'm suggesting that the machine driver for cotton be simplified to this below and delete system16_7759_cotton
```
static MACHINE_DRIVER_START( cotton )
	/* basic machine hardware */
	MDRV_IMPORT_FROM(system16_7759)

	MDRV_CPU_MODIFY("main")
   	MDRV_CPU_MEMORY(cotton_readmem,cotton_writemem)

	MDRV_CPU_MODIFY("sound")
	MDRV_CPU_PORTS(sound_readport,sound_writeport_7759_cotton)

	MDRV_VIDEO_START(system18)
	MDRV_VIDEO_UPDATE(system18)
MACHINE_DRIVER_END
```

**Comment by MistyDreams** [comment]
well do that if you like it was there for the framework for you to update the sound

**Pull request closed without merging**
