### PR TITLE
Remove deadwood dont pull yet

### PR DESCRIPTION
**Pull request by MistyDreams**
remove all un working deadwood if there is no objections to this ill start naming the romsets as they should be and we can working on updating what we dont have. Else its a pointless effort and might as well stop now cause its a bit of a mess at the moment. 

This is better done in one go for users updating sets. Let me know if i go to the next step or naming the sets  just drop it.

### CODE REVIEW

**Comment by arcadez2003** [comment]
Well if we're gonna go down this road might as well do the same for every single driver or just re-enable the warning
screens which will tactually ake care of it and much more besides.

**Comment by MistyDreams** [comment]
well this isnt related to that bug of the screen being removed.  Its to see what sets we can add pointless having ones that dont and wont work and name the sets we do have properly  add one we can that we dont have.

**Comment by arcadez2003** [comment]
YOUR so far single standalone opinion that it's pointless to have non working romsets in the Sega drivers and it's MY so far
single standalone opinion that it's better to leave it em all intact, as far as im aware there are only three of us working on
this core currently so one more opinion to be gleaned.

Maybe if we seek more user input your or my point will win out that is what it's all about is it not.?? i like how you said
your spending more time debating rather than coding it's not your personal pet project your part of a team here so need
to understand that not everyone will agree at all times with whatever direction you wanna take.

I've noticed a trend that it's kinda your way or the highway and if you dont get your way you can react negatively
remember when i started this core i worked on my own i had a vision of what it should be and then more of ya's 
came on board so i feel it pertinent to remind you here many times i did not like the ideas some of ya's came forward 
with over the years but as i said being part of a team and being willing to compromise i reluctantly let ya's get on
with it.

Im but an outside sometime contributor nowadays so i can only but give an opinion or two it's for the owners and
maintainers of this core to give the green light or not to what direction they wanna see this core take.

**Comment by MistyDreams** [comment]
@arcadez2003 I can really figure out your "standalone" comment. Standalone what all we are discussing here is removing protected sets that done even work. I doubt the ever will. 

Im not sure why you would want to even keep them.  I want to add new sets there all named wrong we dont know what sets we using to add new drivers. So we need to clean up and rename them then parent to the sets we using if needed. Then add missing one.

You gave no valid reason for keeping none working sets nothing at all no reason to keep them. Like Ive said I have no strong urge to debate this endlessly it not my way or the highway. Either you want a better driver with more set or randomly named sets not sure what they even are so cant update them. 

Either you want to improve the sets by adding more or keep the old protected ones and wonder what sets are even being used. Its not a completion its improving on what we have. Its not a your way or the highway its not removing things for no reason its to add sets not sure where you coming from at all and dont need to is ok to close and leave it like it is you win lol

**Comment by arcadez2003** [comment]
Infact you know what i withdraw my opinion on this and i'll just withdraw from this core now full stop as i've had a bee in
my bonnet for sometime now considering i created this core and have contributed massively towards it over many years
only to be sacrificed on the altar of the wokie patheticons that reside on social media as the real world is too harsh a
place full of realities they cannot handle.

The owners of this core have clearly made their decision to kick me of a core as i said i created in the first place all to
placate a handfull of MAME dev's with an extremist non mainstream viewpoint who will never rest until they can also
cancel this core.

Oh well you made your bed lie in it more or less.

EDIT apart from the above im also annoyed that my code doesn't seem to be good enough anymore case in point i spend
a day or so outta my life my time to get Action Fighter to work it's 100% in my opinion but hey ho it can somehow be
done better than 100% by someone else same deal with Marble Madness II recently, so i tell ya's what you wont have
that decision to make going forward.

**Comment by arcadez2003** [comment]
> @arcadez2003 I can really figure out your "standalone" comment. Standalone what all we are discussing here is removing protected sets that done even work. I doubt the ever will.
> 
> Im not sure why you would want to even keep them. I want to add new sets there all named wrong we dont know what sets we using to add new drivers. So we need to clean up and rename them then parent to the sets we using if needed. Then add missing ones.
> 
> You gave no valid reason for keeping none working sets nothing at all no reason to keep them. Like Ive said I have no strong urge to debate this endlessly it not my way or the highway. Either you want a better driver with more sets, or randomly named sets not sure what they even are so cant update them even if you wanted too.
> 
> Either you want to improve the sets by adding more or keep the old protected ones and wonder what sets are even being used. Its not a completion its improving on what we have. Its not a your way or the highway its not removing things for no reason its to add sets not sure where you coming from at all and dont need to is ok to close and leave it like it is you win lol

It's not about winning or losing big man but im gone now for reasons unconnected to yourself i've been smarting over
something for a few months now it's time to move on i wish you all the best go ahead and remove them ole romsets
cancel em all :)

**Comment by MistyDreams** [comment]
I dont get half of this @arcadez2003 there is nothing wrong with your action fighter its general improvements that can be done. Im going to close this out of respect. I have no real idea would make more sense for me to leave as I have no affiliation with this project. There was only a small priority issue with the boat not going under the bridges in the intro screen and over them instead its not exactly game breaking.

**Comment by arcadez2003** [comment]
I dont require respect from yourself carry on with what your doin you've done some good work here of late work, i'll have
you know has seriously impressed me and i dont impress easy :) my decision to move on is unrelated to any of this dont
feel you have to do likewise.

Regards

**Comment by MistyDreams** [comment]
My only attachment is to my nieces interest in this stuff. The ole sega games seem crap till you use a bit. I can see why it peaks there interest. 

I thought action fighter was meh at first same with quartet (I felt it ripped off jetpack haha) now i do like these games after giving them a chance. I think sonic put the sega name in there heads to be honest. Just shows kids can show you things your missing out on through not giving them a chance in the first place. Anyway this is off topic I might pick up when mahony finishes his move. Nothing more stressful than moving. Specially when the power and gas company's forget to switch you on!

**Comment by mahoneyt944** [comment]
I'm fairly neutral for these types of things. Removing sets may clean up the length of the driver, but leaving them may attract a dev that wants to take on the challenge to make them work. So it's a coin toss for what's "right".

In regards to action fighter, the leg work to get this game playable is really where the glory goes. I certainly had no desire to do it myself and wouldn't have. However, I do enjoy studying the output and cross comparing it to other emulated sources to push our drivers to be all they can be.

My honest review of action fighter is that it functions very well, it's a playable game and a welcomed addition to the core that many will enjoy. But it's not 100%, not many games are in this core to be fair, so that's not a dig at anyone or a disrespect at the work put in. To expand, this game heavily replies on real time priority adjustments to correctly layer the graphics. In our old code, this is calculated with sys16_bg_prioity_mode 3 and sys16_fg_prioity_mode 3 which compares the games output with a set priority value for each. This will determine if the helicopter flies over the landscape vs the car or boat going below the underpass, while still allowing the car to go over the bridge. Basically we have to adjust the priority on the fly so that the layers align properly for vehicles in their current landscape.

Currently, vehicles pass on top of every junction, i spent a good while testing values and found a value that corrects most cases, about 80% of them. Unfortunately, this value and the value that fixes the remaining 20% contradict each other which brings me to believe that we may need a custom priority mode for this game specifically to have both work. I don't think this would be too difficult though, and maybe there's already a solution in a newer mame to be found. That's all I really know at this point and I'm too tired to go further tonight 😴. I'll take another crack at it soon.

**Comment by MistyDreams** [comment]
Ill just make a branch for my nieces only one driver will sort there roms add a few games they want added. Wont effect anyone beyond them using it. will just apply a diff to retropie for them when they compile saves rebasingg headaches from github. There is a solution for everyone. Its just really too much hassle contributing here from my perspective. 

Good luck with the old video code the segas16a does work for afigher just so you know. If you ever do decide to update on a broken game the code works well. Best of luck on your endeavors.

**Comment by arcadez2003** [comment]
I dunno about glory right enough which can be in short supply when it comes to working on this core i've found it quite
often to be the opposite, it's the challenge more or less for me take code written for different cores and mod it to work
here.

Well your right about Action Fighter upon further testing it's at around 95% still not bad most users would be happy that 
they can now play it where as before it wasn't available here, but yeah if it can be 100% using the later segas16a driver 
then why not take a stab at it, as for removing non working romsets if that's the direction of travel then fair enough i've 
made my views on that clear and that's all they are at the end of the day views more or less.

Im heading over to work on the MAME-NX port now which is basically a core created by lantus aka MVG based on 
MAME72 which he ports to multiple systems and devices, i think it's for the best it's a decision i've mulled over since
last night and for me to continue to contribute here then i need to know im a valued member of the team backed by
the management rather than distant cousin they dont wanna admit they're related to.

In some ways i regret what happened between me and Haze and at the same time i dont i was however upset that it 
was and still is being used as a stick to beat the libretro organization over the head with hence i apologized with you 
guys in mind not him, but at the end of the day you simply have to pick a side you back me or him so until i get my full 
team member status back then i've contributed my final commits to this core the ball as they say is in your court.

There is no hurry here i'll either get the email to join the team again at some point or i wont then i'll know either way
maybe some consideration should be given as to outta the two of us who is more likely to help than hinder.?? 

Well Haze is on a one man mission to destroy this core and likely bring down the whole libretro organization if he could 
where as me i have some viewpoints im not shy to put out there which although are mainstream in nature could also bring down the libretro organization due the current pathetic cancelation culture it's a double edged sword aint it :)

in closing i've stated where i stand i have no desire to discuss this further either here or on discord so @mahoneyt944 
@MistyDreams @markwkidd keep on trucking guys with regards to this core i might catch ya's down the road sometime 
i may not but either way i've enjoyed working with ya's so take care of yourselfs.

**Comment by MistyDreams** [comment]
@arcadez2003 I can understand where your coming form a bit better now. Creating something then ditched and they keep using it. You also have rights ask for your code to be removed if you where thrown under the bus for things beyond you control if you feel strongly about it. You have the rights to your commits regardless of what anyone tells you only you can act on it though.

**Comment by arcadez2003** [comment]
@MistyDreams i have no plans to go down that road right enough im happy for all my contributions to remain here
as i said above in order for there to be anymore going forward then what i stated above has to happen that's it 
more or less.

Regards.

**Comment by MistyDreams** [comment]
seems a fair level headed choice and your being the bigger person here hats off to you. I hope they see some sense if not will be a loss to project;

**Comment by arcadez2003** [comment]
Well it would be petty and at the end of the day i'd be punishing the users and making life difficult for the devs on here
but for the record the reason i reacted the way i did towards Haze was because i thought all my commits would have to
be removed as he made that licence violation submition.

If i'd known it was only gonna turn out to be one game Beyond Kung Fu more or less i wouldn't have bothered so much 
oh well  ya live ya learn and yeah as per the above me asking for code to be removed was never gonna happen :)

**Comment by MistyDreams** [comment]
well dont know any details but its seems your only blaming haze. All that has to be done a violation of licensing is either rework it, or remove it and acknowledge it. Removing you from the project was not required for any of this if haze said this its not true and they have over reacted. People get pissy all the time. Unless a ethical violation of some sort happened I dont see a code of conduct anywhere could have missed it.   

If they kicked you out on there own backs thats not a requirement neither is your personal issue with others. The person that made that choice is square to blame. In summary If its a bigger picture problem than you and haze that you hinted at before you where thrown under a bus then smacked with a train. Dont doubt that for one minute just cause you made a mistake does not mean you become damage control and not supplied an ambulance.

**Comment by mahoneyt944** [comment]
Not my fight to discuss but I don't think it was the violation so much as the slander and language used which reflects on libretro.

**Comment by mahoneyt944** [comment]
Btw @arcadez2003 should have this straightened out for you in a minute

**Comment by arcadez2003** [comment]
> Not my fight to discuss but I don't think it was the violation so much as the slander and language used which reflects on libretro.

Sure i understand that it was discussed at the time i can 100% guarantee there will no repeat performance.!!

**Comment by arcadez2003** [comment]
> Btw @arcadez2003 should have this straightened out for you in a minute.
> 
> Edit. Just hit accept and let me know it worked right for you 👍

All good thanks

**Comment by MistyDreams** [comment]
better out than in @arcadez2003  :)

**Comment by arcadez2003** [comment]
> better out than in people cant guess how your feeling @arcadez2003 :)

Well obviously im happy to be back but in some ways im still raging about all this not with LB/RA as i fully understand 
the damage limitation excersise they had to undertake and what's more i agree it had to be done.

My take on this is that my words were twisted back to front by someone with an agenda a simple ploy to link what i said
in with past events with a view to combine them in an attempt to damage the reputation of the libretro organization im 
sure this will continue on unabated in certain circles searching most likely for the next stick to beat us with as type this.

Sure some of what i said to him was plain nasty another level of nasty some might say and being honest here some of it i 
do regret but i could paste in here multiple examples over the last few years of where he's said something akin to the same level of aforementioned nastiness towards me over on reddit, no whataboutery here im just sayin you cant play the victim 
card when you've been many times the villian previously.

Anyway going forward is the plan not looking back so i wont broach this subject again if there is further drama regardless of who is causing it im just going to ignore it and let the management deal with it as they see fit.

Regards

**Comment by MistyDreams** [comment]
well the pull request went to shit but think something good came of it haha

**Comment by arcadez2003** [comment]
> well the pull request went to shit but think something good came of it haha

If at first you dont succeed then keep pulling it until you do :)

**Comment by MistyDreams** [comment]
not even commenting on that haha

**Pull request closed without merging**
