### PR TITLE
Nbajamte is parent

### PR DESCRIPTION
**Pull request by mahoneyt944**

### CODE REVIEW

**Comment by mahoneyt944** [comment]
@MistyDreams do you agree with this? Later mame has this as its own parent

**Comment by mahoneyt944** [comment]
It does share a few with nbajam, but I believe it's different enough that later mame separated them

**Comment by arcadez2003** [comment]
No complaints from me

**Comment by mahoneyt944** [comment]
sounds good. found this too which confirms train of thought
https://github.com/libretro/mame2015-libretro/commit/dad99e71075c0725940704aa040293bb37ab77ab

**Pull request merged**
