### PR TITLE
Input cleanups

### PR DESCRIPTION
**Pull request by markwkidd**
This PR comes a little more directly from my work to add support for the newer parts of the libretro lightgun API.

I am doing some basic sanity testing to make sure that these refactors haven't introduced a regression before I convert this PR from draft to merge-able. I believe that there are further simplifications to all this code but this would be a key step in cleaning it up.

### CODE REVIEW

**Comment by mahoneyt944** [comment]
@markwkidd I cleaned up some spacing issues, the tab vs space junk.

**Comment by markwkidd** [comment]
@mahoneyt944 thank you. when I started contributing to this core again, I switched to the Visual Studio IDE and I need to figure out how to set it to point that kind of problem out to me

**Comment by mahoneyt944** [comment]
I just peak here, under "files changed", to see if any spacing looks off in the comparison. Not the most high tech method but works.

**Comment by mahoneyt944** [comment]
Btw, nice go at slashing down all these abundant defines and such. It looks like my spacing goofed up your last merge / sync though. Opps :(

**Comment by markwkidd** [comment]
Ack, I manually resolved the merge conflicts so I thought I had taken care of that. I'll redo those spaces momentarily.

Thank you for the encouragement. I feel like now I've been able to figure out how to graft in the new lightgun stuff even without refactoring, but I honestly hope that these changes will make it faster next time someone (including me) tries to figure out how to make a change or addition.

**Comment by mahoneyt944** [comment]
Check the spacing issues in:

void retro_run (void)

**Comment by mahoneyt944** [comment]
And in

 int osd_is_joy_pressed(int joycode)

**Comment by mahoneyt944** [comment]
I just tested this as of 0d0d155. And no inputs are working at all.

**Comment by markwkidd** [comment]
Yep, somewhere in refactoring I've managed to kill RetroPad input altogether. 🕺 

Fixing the return statement was essential, but even though I wanted that to magically restore RetroPad input too, there's still no RetroPad input even after the fix.

Hopefully there's just a line screwed up somewhere and I only need to find it...

**Comment by mahoneyt944** [comment]
Check the log, make sure the controllers are initializing properly

**Comment by mahoneyt944** [comment]
You probably want to initialize player_index too in osd_is_joy_pressed.

int player_index, osd_code = -1;

Should be:

int player_index = -1, osd_code = -1;

**Comment by mahoneyt944** [comment]
I added some cleanups and commented out the reversal code for now. It doesn't seem right how it was changed but can't test with the inputs broken ha. 

The reversal code is meant to allow the users to map things oppositely.....up as down and left as right, for use in flight stick games.

**Comment by mahoneyt944** [comment]
ok, so I merged the last working commit of this wip to master. https://github.com/libretro/mame2003-plus-libretro/commit/eb2039b1d34e41c2bb79a382f67c12e97ab8fefe

you'll probably have to close this and resubmit your changes to the new master or rebase this branch.

thoughts......
- in function : osd_is_joy_pressed : "if(osd_is_joystick_axis_code(joycode))" does its check but then returns the retroJsState at the end of the fuction regardless.
- Should osd_is_joy_pressed always return? or return 0 by default?

**Comment by mahoneyt944** [comment]
ok, so I merged the last working commit of this wip to master. eb2039b

you'll probably have to close this and resubmit your changes to the new master or rebase this branch.

thoughts......

- in function : osd_is_joy_pressed : "if(osd_is_joystick_axis_code(joycode))" does its check but then returns the retroJsState at the end of the fuction regardless.
- Should osd_is_joy_pressed always return? or return 0 by default?
- calc_player_index, should it return i - 1?

**Comment by mahoneyt944** [comment]
Im going to open a new pr for this since the commits are goofed up.

**Pull request closed without merging**
