### PR TITLE
add the buttons to stick hack back

### PR DESCRIPTION
**Pull request by grant2258**
ill add this properly when we add the analog controls in but we should leave it functional

### CODE REVIEW

**Comment by Wilstorm** [comment]
Ha, so, well I already went through and remapped all the incorrect inputs and everything works fine, time to undo it. But after this update I should delete my ROM configs for those games and the defaults will work properly? Thanks I guess I had no idea it was a quick fix and have accepted weird inputs as is for some games.

**Comment by Wilstorm** [comment]
I'm not sure if the update was meant to address Super Smash Bros., Total Carnage and Cloak & Dagger right stick firing but it's still the same issue but just reintroduced double inputs in the MAME TAB. I can open a new issue as out of the box these games are not playable using default controllers mappings per the Retroarch diagram.

**Comment by grant2258** [comment]
Am at work will look when I get back

**Comment by Wilstorm** [comment]
Thanks good sir and have a good weekend!

**Comment by grant2258** [comment]
@Wilstorm some changes we do require a clear of default mame mapping configs it saves. It doesnt happen very often this is one case it does need done. 

The pull request is in for the fix it was a simple fix just had to get to work so pushed it without testing.

**Pull request merged**
