### PR TITLE
kof game add

### PR DESCRIPTION
**Pull request by odarknighto**
The new game source code is from mame103,104,105

### CODE REVIEW

**Comment by odarknighto** [comment]
The new game source code is from mame103,104,105

**Comment by arnoldsecret** [comment]
Question, have you tested KOF 2003, changes in decryption code for neogeo in later versions might break what we have right now.

**Comment by odarknighto** [comment]
> Question, have you tested KOF 2003, changes in decryption code for neogeo in later versions might break what we have right now.



> Question, have you tested KOF 2003, changes in decryption code for neogeo in later versions might break what we have right now.

I had test kof2003 and work fine,I just add so I haven't change kof2003d init,and kof2002 I have change Decrypt way like mame103 and work fine

**Comment by odarknighto** [comment]
By the way,I only test with my Nintendo switch because compiler easy than other platforms,sorry><

**Comment by arcadez2003** [comment]
@odarknighto if you've tested the changes and there is no game breakage with regards to kof2002 / kof2003 / kof10th
and there are no compile issues then we can push it to mainline thanks for your contribution

It'll be good to actually support the proper version of kof2003 in this core i didn't think it was doable due to the 
aforementioned changes to the neogeo decryption circa MAME 103 i guess i was wrong :)

**Comment by odarknighto** [comment]
> @odarknighto if you've tested the changes and there is no game breakage with regards to kof2002 / kof2003 / kof10th
> and there are no compile issues then we can push it to mainline thanks for your contribution
> 
> It'll be good to actually support the proper version of kof2003 in this core i didn't think it was doable due to the
> aforementioned changes to the neogeo decryption circa MAME 103 i guess i was wrong :)

actually kof2003 I used mame104 source because p3-decrypt  is difficult to find and mame104 can use encrypt p3 and play well
Those add game I had try and can play😀

**Comment by odarknighto** [comment]
> @odarknighto if you've tested the changes and there is no game breakage with regards to kof2002 / kof2003 / kof10th
> and there are no compile issues then we can push it to mainline thanks for your contribution
> 
> It'll be good to actually support the proper version of kof2003 in this core i didn't think it was doable due to the
> aforementioned changes to the neogeo decryption circa MAME 103 i guess i was wrong :)

I don't know other game because I just try add kof game,but I can promise I haven't edit other game driver ><

**Comment by odarknighto** [comment]
> @odarknighto if you've tested the changes and there is no game breakage with regards to kof2002 / kof2003 / kof10th
> and there are no compile issues then we can push it to mainline thanks for your contribution
> 
> It'll be good to actually support the proper version of kof2003 in this core i didn't think it was doable due to the
> aforementioned changes to the neogeo decryption circa MAME 103 i guess i was wrong :)

About neogeo decrypt I haven't change anything so it's ok

**Pull request merged**
