### PR TITLE
Tatsumi add files for arcadez

### PR DESCRIPTION
**Pull request by MistyDreams**
Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by mahoneyt944** [comment]
@MistyDreams error reports:
tatsumi.c:700:34: error: use of undeclared identifier 'PI'

**Comment by mahoneyt944** [comment]
Pushed this https://github.com/libretro/mame2003-plus-libretro/commit/57c5796c48bb466591495cfae7e0d4d09dc42690

Assuming that's what it was after?

**Comment by mahoneyt944** [comment]
That's a lot of them.
Screenshot_20230121-111327

**Comment by mahoneyt944** [comment]
I did this for now. https://github.com/libretro/mame2003-plus-libretro/commit/86b4abf6b2845ccfe699cd6c306498bbd6facbf9

**Comment by mahoneyt944** [comment]
You can relocate it more appropriately if you want. Was just trying to get it compiling again. However you prefer is fine.

**Comment by mahoneyt944** [comment]
Not sure exactly I think @m4xw does?

**Comment by mahoneyt944** [comment]
Unfortunately still more compiler issues
Screenshot_20230121-124508

**Comment by mahoneyt944** [comment]
Think I got it now.

**Comment by arcadez2003** [comment]
Sorry fellas i missed that INLINE change which i needed to make :)

**Comment by arcadez2003** [comment]
@MistyDreams Do you have testing cores based on later MAME say 84 for example.??

**Comment by arcadez2003** [comment]
Fancy taking a peek at this cast your eye over the changes to see if you notice a mistake or two i might have made
as things stand the both games stall on boot i think it's the watchdog but not totally 100% on that.....
[tecmosys WIP.zip](https://github.com/libretro/mame2003-plus-libretro/files/10473174/tecmosys.WIP.zip)

**Comment by arcadez2003** [comment]
Im still trying stuff but unlike yourself i'd only be guessing here it's a bugger to not have well a debugger :) 

I've added @mahoneyt944 palette inlines to use pal5bit directly instead of an ole hack iq_132 added for use with other
games which i lifted from another driver maybe with a bit of luck that will be the issue.......

INLINE void set_color_555(pen_t color, int rshift, int gshift, int bshift, UINT16 data)
{
//#define pal5bit(n)	((((n) & 0x1f) << 3) | (((n) & 0x1f) >> 2))

	palette_set_color(color, pal5bit(data >> rshift), pal5bit(data >> gshift), pal5bit(data >> bshift));
	
//#undef pal5bit
}

**Comment by arcadez2003** [comment]
Well that didn't help here are the 3 things that worry me in order of worryness levels :)

1)
MDRV_WATCHDOG_VBLANK_INIT(400) // guess

Cant support this as yet it's my most likely cause but hey i might be totally wrong here
2) 
	//	if ( video_screen_get_vpos(machine->primary_screen) >= 240) return 0;
			if ( cpu_getscanline() >= 240) return 0; // correct.??

Checked a fair few drivers vs the above im pretty confident this is how you handle this 78 - 84

3)
					//dstptr = BITMAP_ADDR16(sprite_bitmap, drawy, drawx);
                    // dstptr = ((UINT16 *)sprite_bitmap->line[drawy])[drawx];
                  // UINT16 *dstptr = ((UINT16 *)sprite_bitmap->line[drawy])[drawx];
		           dstptr = &((UINT16 *)sprite_bitmap->line[drawy])[drawx]; // correct seems like the only way which will compile.??

Im not sure the above is correct it's the only way i can get it to compile without warnings around  redefinitions of 
		UINT16* dstptr;

**Comment by mahoneyt944** [comment]
It's getting harder and harder to sort code on my mobile. Not sure if it's GitHub or chrome but the text bunches so much it hard to read anything, even in desktop mode. Though I'm way over due for a new phone, that may help.

**Comment by arcadez2003** [comment]
Yeah the watchdog is used to send protection commands back and forth from the CPU's that will explain as to why
the games are stalling on boot im hoping a workaround can be found as i dont fancy having to update all the watchdog
code to MAME88 so we can use.........

MDRV_WATCHDOG_VBLANK_INIT(400) // guess

Been dabbling with the code but no joy yet....

static void watchdog_reset(void)
{
	if (watchdog_counter == -1)
		logerror("watchdog armed\n");
	watchdog_counter = 3 * Machine->drv->frames_per_second;
}


WRITE_HANDLER( watchdog_reset_400_w )
{
	watchdog_counter = 400;
}

**Comment by arcadez2003** [comment]
Thanks i've added the bitmap calls gonna switch the tecmosys driver to use em

**Comment by arcadez2003** [comment]
> Still need to get mame084 to compile for the bitmap stuff. iIadded the macros to our core here https://github.com/libretro/mame2003-plus-libretro/blob/master/src/common.h#L43-L48 its something worth adding if mame084 doesnt have it.

I'll convert the driver to MAME78 later so we have more options :)

**Comment by arcadez2003** [comment]
Here is tecmosys.c further backported to MAME78
[tecmosys 78.zip](https://github.com/libretro/mame2003-plus-libretro/files/10475186/tecmosys.78.zip)

**Pull request merged**
