### PR TITLE
 Avengers in Galactic Storm FIX dont pull untill arcadez reviews the code

### PR DESCRIPTION
**Pull request by grant2258**
Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by markwkidd** [comment]
@grant2258 could you look to see if the avengers description looks right for these romsets? This would be a good moment for me to activate these control names if they're correct

**Comment by grant2258** [comment]
will do mark well its only saying button 1, button 2, button 3 and button4 one of the buttons is mapped  its 2 kicks and two punches

1 & 2 are punch buttons
3 & 4 are kick buttons

**Comment by markwkidd** [comment]
Thanks for looking at the controls Grant, you're right I can see the controls.dat project had an incomplete set of labels. This is only the second time they're not correct but that's why it's good to check! I'll see about correcting the descriptions and then enable them

**Comment by markwkidd** [comment]
oh wait I see you already corrected the controls :D thanks!

**Comment by grant2258** [comment]
no problems no point in not doing it :)

**Pull request merged**
