### PR TITLE
Opaopa

### PR DESCRIPTION
**Pull request by MistyDreams**
game is playable dont pull until somone fixed the rest of the ports done the service. Also add the batman.h as it isint being tracked in master.

### CODE REVIEW

**Comment by mahoneyt944** [comment]
Already have the inputs hooked up in another PR. Not sure what you mean about batman.h, you can re- PR that though

**Comment by MistyDreams** [comment]
they are wrong game wont start ytour using system16 input ports. Ill leave this for someone else to sort probably my last commit here the way things are done :)

**Comment by mahoneyt944** [comment]
I beat the fist level already? It's works fine? You must be looking at an older commit

**Comment by MistyDreams** [comment]
```

void segas16b_state::standard_io_w(address_space &space, offs_t offset, uint16_t data, uint16_t mem_mask)
{
	offset &= 0x1fff;
	switch (offset & (0x3000/2))
	{
		case 0x0000/2:
			//
			//  D7 : 1 for most games, 0 for ddux, sdi, wb3
			//  D6 : 1= Screen flip, 0= Normal screen display
			//  D5 : 1= Display on, 0= Display off
			//  D4 : 0 for most games, 1 for eswat
			//  D3 : Output to lamp 2 (1= On, 0= Off)
			//  D2 : Output to lamp 1 (1= On, 0= Off)
			//  D1 : (Output to coin counter 2?)
			//  D0 : Output to coin counter 1
			//
			m_segaic16vid->tilemap_set_flip(0, data & 0x40);
			if (m_sprites.found())
				m_sprites->set_flip(data & 0x40);
			if (!m_disable_screen_blanking)
				m_segaic16vid->set_display_enable(data & 0x20);
			m_lamps[1] = BIT(data, 3);
			m_lamps[0] = BIT(data, 2);
			machine().bookkeeping().coin_counter_w(1, data & 0x02);
			machine().bookkeeping().coin_counter_w(0, data & 0x01);
			return;
	}
	logerror("%06X:standard_io_w - unknown write access to address %04X = %04X & %04X\n", m_maincpu->pc(), offset * 2, data, mem_mask);
}
```

**Pull request closed without merging**
