### PR TITLE
Added Core option to disable cyclone

### PR DESCRIPTION
**Pull request by apison**
Added Core option to disable cyclone

### CODE REVIEW

**Comment by mahoneyt944** [comment]
@grant2258 what do you think about moving init_core_options() in this PR?

Also seems repetitive to set options.enable_cyclone in retro_load_game. Is this necessary or should we just add the (restart core) like the other core options?

Thoughts?

**Comment by grant2258** [comment]
Im guessing only the op didnt want to be invasive with the code he was adding. This code can be re factored to be added here

https://github.com/libretro/mame2003-plus-libretro/blob/00f5bab589865ea3f5cd9a8596a6b2ac6bc39f73/src/mame2003/mame2003.c#L287

https://github.com/libretro/mame2003-plus-libretro/blob/00f5bab589865ea3f5cd9a8596a6b2ac6bc39f73/src/mame2003/mame2003.c#L416

**Comment by mahoneyt944** [comment]
And it appears that this is uneeded. As it should get cause in the else's default below. Correct?
```
  /* none - cyclone core option */
  else if (options.enable_cyclone==0)
  {
    use_cyclone = 0;
    use_drz80_snd = 0;
    use_drz80 = 0;
  }
```

**Comment by grant2258** [comment]
nah it is needed because its all set 1 as default and disables as needed.

**Comment by apison** [comment]
Im not a c++ programmer and above all im not a retroarch expert so all the modify that improve the option are very well accepted.

**Comment by mahoneyt944** [comment]
@grant2258 if we removed that section and the core option was set to "none" (0). That means the "cores" variable would = -1 so no case would match and the default catch sets the same thing? Or am I seeing things wrong?
```
      default:
        use_cyclone = 0;
        use_drz80_snd = 0;
        use_drz80 = 0;
```

```
  /* none - cyclone core option */
  else if (options.enable_cyclone==0)
  {
    use_cyclone = 0;
    use_drz80_snd = 0;
    use_drz80 = 0;
  }

  /* Force cyclone with user selected core option */
  else
  {
    int cores=0;
    cores=options.enable_cyclone-1;

    switch (cores)
    {
      case 0:
        use_cyclone = 0;
        use_drz80_snd = 0;
        use_drz80 = 0;
        break;
      case 1:
        use_drz80_snd = 0;
        use_drz80 = 0;
        break;
      case 2:
        use_cyclone = 0;
        break;
      case 4:
        use_cyclone = 0;
        use_drz80 = 0;
        break;
      case 5:
        use_drz80 = 0;
        break;
      default:
        use_cyclone = 0;
        use_drz80_snd = 0;
        use_drz80 = 0;
        break;
    }
  }
```

**Comment by grant2258** [comment]
code looks good its wrapped round an if else to catch it. It does need re factored though. Problem is this only changes on reloading the core instead of real time.

**Comment by apison** [comment]
The default settings should be used to use the  fe_drivers struct cyclone configuration that in most cases is the correct ones.

**Comment by mahoneyt944** [comment]
@apison I updated the default core option already to use the default first

**Comment by grant2258** [comment]
I dont know really I personally think this makes the list redundant anyway. Do we really need all them options on or off for each core should be fine. You would need to tie in with mark on this. From what i can see @apison  added the feature he wanted and still lets the list work if that is wanted. I think this is confuing for users though on and off is more clear.

**Comment by mahoneyt944** [comment]
I think the idea is to be able to override the default cyclone settings and experiment with what works? It's disabled for most platforms anyhow. 

I think it just needs really optimized / cleaned up.

**Comment by mahoneyt944** [comment]
This PR should function the same as the core does now except the user can override the default cyclone settings using the core option now. The limitation right now is the core needs a full reboot after changing this setting for it to take effect.

**Pull request merged**
