### PR TITLE
Street Fighter 1 Custom OST Support!

### PR DESCRIPTION
**Pull request by KMFDManic**
Personal thanks to Kurrono for his amazing collaborative efforts in helping improve MAME 2003 Plus/Xtreme for the better with fantastic Custom OST support for Street Fighter 1 AKA Fighting Street!

**TEMP DL for Samples Zip File, which goes into libretro/system/mame2003-plus** 

https://drive.google.com/drive/folders/13nRcURPckpUCxjpRCG8iKYe54SEKYbhu

**Demonstration Video of this commit in action!**

https://www.youtube.com/watch?v=0sDyCH02Yto

**An example of RoboCop with Movie OST, by the way, he had already done for MESEN, which I feel would be nicely suited to the MAME dec0 driver!**

https://www.youtube.com/watch?v=keESnjaVm38

Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by mahoneyt944** [comment]
We need to convert this to the updated format used in ost_samples.c before we can merge. I don't have time right now but I can in a couple of weeks.

**Comment by MistyDreams** [comment]
Not going to do any needless code refactoring requested above but I can test the pull request if it needs tested.

**Comment by arcadez2003** [comment]
With all due respect and all is it not upto those that created the code to fix and align it with our core.

**Comment by mahoneyt944** [comment]
I didn't ask him to refactor it, I said I would do it. And it not "needless", if you actually follow the logic there's many issues with the old format. Many conditions that are never set, variables that aren't used, etc.

Besides that, it looks like there maybe just general issues such as sf1_start isn't being set to true anywhere, which means those samples will never play.

**Comment by KMFDManic** [comment]
@mahoneyt944 @MistyDreams @arcadez2003 For the record, the way the coding "should" work, is it is default to "off" for samples.  But, if you enable "use samples" in the MAME 2003 Plus Core Options, they "should" be valued as "true", at that point.  My very first test with this coding was with 2003 Plus:)  I didn't have any issues running the samples.  I toggled Use Samples OFF, Samples didn't play on a reload of the game.  I toggled Use Samples ON, they played fine, from beginning to end, and "seemed" to trigger at all the correct "hooked" spots.

In Xtreme, which "always" has Samples ON, SF1 is always "true", as are any other games, as libretro/system/samples/mame2003-xtreme/samples "exist" here, they play, always (even if coding is set to false, since there doesn't appear to be any true/false (core) option variable to draw back on).  I MAY add the Core Option so people can select them as On/Off.  But, usually when people DO want that ability, I just suggest they use the nice companion piece to Xtreme...Plus:)

Feel free to test the coding and samples, On/Off Samples Core Option, with the sf1.zip I dropped, in mame2003-plus samples folder.  You should be able to fully play the game, without issue.  Again, if there is a conflict or discrepancy, that any of you feel should be fixed up, don't hesitate to bring it to light!  From my testing, however, I was fine running SF1 on Plus/Xtreme.  Hopefully, you are fine on it, as well!!!  

Anytime checks/error messages pop up, compile process, or otherwise...it is still always good to double check.  But, sometimes, magic happens, regardless:)  Almost reminds me of the "Scam" artists who call phones saying, "your computer has issues with Windows..you have many error messages!"  But, we all know, by now...Every second that passes on Windows, is probably another logged error or few, hehe:)

If an error prevents a Core from compiling, completely, then yeah, that is for sure a problem!  That would be like a Red Traffic Light!  But, I am pretty sure all of us have run into the Yellow Light equivalent Errors that show up during compiles and checks, that really seem to be more like a "stern caution", more so than a warning, as these tend to "still work", despite whatever generates as a caution.

Definitely test the coding with the samples out, and have a little fun playing the game:)  And, feel free to convert, adjust, or whatever to the coding, if need be.  I am more than happy to keep helping get new kickassery into 2003 Plus, as well as in Xtreme!  

Last thing I will ask about, for now...Kurrono mentioned he had previously been able to compile 2003 Plus fine with his compiler setup of MinGW/MSYS2.  But, now, something changed, which has led to him being unable to compile 2003 Plus, even from mainline source.  If any of you build and test it on Windows, maybe a few tips that would help him get up and running again?  I will get MinGW/MSYS2 going again, as well, so I can be on the same page as him.  I have mostly done these Cores on Mini Classics, and less so needed to build and test them on Windows, of late.  But, if I am gonna be part of getting more of these commits, moving forward, into 2003 Plus..I will definitely start testing on PC, as well as the Minis!

Potential ideas, after SF1, will be Contra with Contra Evolution OST, Robocop with Movie OST, and so on.  Feel free to suggest any that might make Plus/Xtreme even more fun to experience!

**Comment by mahoneyt944** [comment]
Sf1 is a valued addition. I didn't mean to come off as otherwise just to be clear. Not too long ago I created ost_samples.c and rewrote the ost code to be a bit easier to work with. My thought was to contain the ost code as much as possible in one place so updates and additions could be done very easily. Not to mention being less invasive into the drivers which should prevent accidental breakage of the ost code when drivers are updated.

Also I figured it maybe worthwhile for other cores to port the ost code as an isolated file if anyone wanted to do so.

But again this is great work, the time to find the hooks is where the value is. Structuring the ost stuff is just boring house keeping.

**Comment by MistyDreams** [comment]
I dont have the ost samples but looking at the code final fight and sf2 all the sets that init in the machine sf2 is particularity problematic with the amount of  children linked to it sf2ce ect not sure if this is an oversight or not

**Comment by KMFDManic** [comment]
@MistyDreams As a slight refresher.  Street Fighter II was first added to Xtreme, then Plus, then temporarily removed from Plus, til it was decided on how to best proceed re-adding it.  This is exactly one of the reasons Samples On/Off Option was added.  If someone decided they do not want to run with Samples, they can just toggle the option off, and/or simply not have the samples at all.  You'd just get a "samples are missing" error message, and the game would revert to the default soundtrack.  In testing, things have been fine for several of us.  The nicety of Samples On/Off has made it an easier to digest addition.  All 7 of the previous Custom OSTs have been extensively tested, and work great on Plus/Xtreme.  I also fully played the 8th one, as did Kurrono, and that worked out well, too, on Plus:)

Once all is said and done, if we can get his Compiler fixed up, then it will be a lot easier to collaborate on future Custom OSTs, as well!  They are easily one of my absolute favorite additions to Plus/Xtreme!

**Comment by MistyDreams** [comment]
Thats my aim to get the compiler fixed for kurrono that's putting the work in. Its simple enough to fix you just need to add a sound tag. Im more interested in helping the dev getting his setup working rather than how to implement it at the moment. I think its really impolite to take over someone else's work instead of helping them with the real issues at hand. Maybe im just old and stuck in my ways. I find working with people and wording things less micro managed style comments goes a really long way.

**Comment by MistyDreams** [comment]
Regarding the ost working on all clones this is easily fixed to work on only the games that it should work on. I know ff and mk used to only work on the one rom with ost enabled in plus anyway

**Comment by mahoneyt944** [comment]
This core has two sample options, one for all samples usage and one for ost sample usage. This allows the user to disable all samples or only disable ost samples. As far as clones using ost samples, there are likely clones that will also work, however some may not. Lots of testing would be needed for this to be proven out. The above options however allow a user to bypass this either way so it shouldn't be much of an issue. It's difficult to decide to remove clones because there's always someone using a different language from that wants the samples which is why I left the option open to the user.

**Comment by MistyDreams** [comment]
the roms the samples are for are clearly in the name for the specific set its meant seems this is an oversight when it was converted to a new format maybe: If you happy with this setup it fine will put users off if it messes other games up. Defo would put me off if untested games mess up using them. I can see the osd is picked up with the sound tag check anyway its just the rom name check name missing that could avoid this is it wasnt wanted.

**Comment by mahoneyt944** [comment]
And maybe I did come off as rude so I'll apologize, I have no intention of taking over someone's development. But ost was updated in this core so splitting it again seems like the wrong play..... which is why I offered to convert it here, at my expense, as to not burden a dev with house keeping stuff. Doesn't seem like a big deal to me but if anyone would prefer I not be involved or do this conversion, I'll surely let you guys do whatever you want with ost.

**Comment by MistyDreams** [comment]
nah its not really an issue, being helpful sometimes comes across as micro managing if it can read the wrong way. 

People get in knots online all the time. I read the issue as the dev was having problems compiling this core and now that has been solved. Its all how you word things. Asking if you want to do it for them or they would want to do it makes a world of difference. When talking online things come across very mono at times. It seems more so with devs logical thinking out loud many times comes across the wrong way.

**Comment by mahoneyt944** [comment]
Well I went ahead and converted it into a branch. https://github.com/libretro/mame2003-plus-libretro/compare/Sf1

I suspect outrun was used as a model to get this going based on the variable naming and structure.

Anyways had some questions / findings:

1.  Do we want the driver to initialize `sf1_start = true;`? This variable is never set to true so it won't play these ever on start.

2. Sample 31 was missing due to a typo with the sample number. 

3. It seems there's lots of variables we are setting and not using. Do we want to remove these?

**Comment by KMFDManic** [comment]
@mahoneyt944 The looping is something that comes with the territory.  It is also an issue with MSU-1 for SNES, MSU-MD, etc.  Some who are less adept at handling it, may put out Custom OSTs that can be a little too distracting, when the "loops" come in.  Others, are creative for how they handle it, and most will usually complete a stage before there is a remote chance of looping.  Some of them, once the track finishes, if it doesn't loop, you will have NO music, which is worse than just repeating the music:)  This is why we try to effectively use samples that are JUST long enough to cover the stages, for the most part!

@kurrono will see this, and we can make adjustments, moving forward..to account for stuff.  But, disabling loops may be a bad idea, since it would just stop the music and have no sound..People might think games are glitching, if that occurs.  I found the loops were fine, and didn't happen too frequently!  

Again, we can discuss things, and make the best decisions.  2003 Xtreme, I will do testing with that Core, as well as Plus.  I will commit the changes to Xtreme, and let you all know about them, here, and we can all work as best we can as making them nicely functional on both fronts.

Again, thanks @kurrono, as well as @arcadez2003 @mahoneyt944 @MistyDreams for your continued efforts in making this a harmonious place to hang out and help the MAME cause:)  2003 Xtreme and FBNEO Teams have always been incredible with me, as far as fixing things up.  This is why they are 2 of the Cores I thoroughly enjoy in trying to get some of my creative input into!  I do others, as well.  But, Arcade Games have always been my lifeblood, and the reason I got a computer to begin with, in the late 1990s!!! MAME For Life, I say, as well as FBNEO:)

**Pull request closed without merging**
