### PR TITLE
Killer Instinct 1 and 2 Cheats Update!

### PR DESCRIPTION
**Pull request by KMFDManic**
Here ya go, @mahoneyt944 

**Disclaimer: Being that this the initial addition of massively updated KI1 and KI2 Cheats, please do not expect all Cheats to fully function as advertised!  Some of the Cheats may be subject to change in future Updates!**

Killer Instinct 1 and 2 Cheats Update!
Killer Instinct 1: Attack and Movement Speed Manipulation via Updated Cheats (cheat.dat)!

Selection of 12 different speeds and 21 different sizes, including Defaults.  You can choose to move as slow as molasses, or as fast as a Jedi!  Fight as a metaphorical watching paint dry sloth, or as frenetic as a one inch punch from Bruce Lee!  You can also be as small as a mouse or as large as a Kaiju!

Dozens of other Cheats added for both Killer Instinct 1 and 2, including Automated Ultra Combos and Humiliations and No Mercy Finishers!

Personal thanks to Mahoneyt944 and Abystus for their incredible efforts and insight in this little project I personally wanted to implement to help better lower spec platforms!

retroarch/system/mame2003-xtreme/cheat.dat

retroarch/system/mame2003-plus/cheat.dat

If using 2003 Plus, you must delete the .rzip, before the new cheat.dat will take effect!

R2 to open MAME Menu on 2003 Xtreme; L3 or Core Options to do the same for 2003 Plus.

Select Cheats, Apply, Resume Game, Rinse and Repeat, Enjoy the Performance/Speed Boost!

Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by KMFDManic** [comment]
@mahoneyt944 Hopefully, testing is going well on your end.  I made one more revision, and after a few hours testing, am satisfied at leaving things where they are for now!  

Nice and Easy Volume Control, without needing to go through the Dip Switches.

https://github.com/KMFDManic/mame2003-xtreme/commit/3031e335c8980295f2e9c3e0fece5aea38320b95

**Comment by mahoneyt944** [comment]
Some of the kinst2 cheats need corrected, they shouldn't begin with ```@```

**Comment by KMFDManic** [comment]
@mahoneyt944 Just let me know what you feel needs adjusted, and I will get it done!  I can easily do another pull request.  I know, perfection takes a few tries:)  No rush on this.  Just want you to be happy with the end result.  Did you get to try some of the Cheats out for either game, as of yet?

**Comment by KMFDManic** [comment]
@mahoneyt944 Test Demonstration with some of the KI 1 Cheats I updated.  This is on RetroPie 2 equivalent hardware.  So, you can see things truly make a difference, especially when you compare the starting stage!

https://www.youtube.com/watch?v=bb7I1Blhe5Y

Once you are content with what you need me to finalize, let me know, and we can go from there!

**Comment by KMFDManic** [comment]
@mahoneyt944 Was there any particular reason why some of the later cheats formatting included @ in them?  And, just going over an even newer XML format, and that setup, it is quite interesting how that adapted, too!

**Comment by KMFDManic** [comment]
These are the ones I am referring to.  In future revisions, I will likely try to go between the "last" cheat.dat we can use, which I dropped for you a few days ago, and ones from the newer xml cheat format.  At least we have options!

[kinst1_and_2_xml_cheats.zip](https://github.com/libretro/mame2003-plus-libretro/files/8701106/kinst1_and_2_xml_cheats.zip)

**Comment by mahoneyt944** [comment]
It might be because they are part of the same code. I need to look into it more before merging. However, I've been sick and haven't been on here much do to it. I will though

**Comment by KMFDManic** [comment]
@mahoneyt944 Take your time.  Once you are satisfied, let me know, and I can do another pull request if necessary.  I work all week, and likely won't get a chance to do a lot more til later in the week.  So, rest up, watch a movie or few, binge watch a tv show!  Ozark is a fun one:)  But, get better!  And, we shall chat again, soon!

**Comment by KMFDManic** [comment]
@mahoneyt944 Last statement I will make for now.  The cheats for KI2 that have @ in them appear to be all of the ones that are most optimal with "activation keys".  You are still welcome to decide how we roll out the final dat, however!  I will chat with you whenever you have time, this week!

**Comment by mahoneyt944** [comment]
@KMFDManic I went ahead and merged this. I did notice that you were trying to expand the speed options. While any number of values can work here, you may want to test the full hex range of values (0 - F). or:
```
00000001
00000002
00000003
00000004
00000005
00000006
00000007
00000008
00000009
0000000A
0000000B
0000000C
0000000D
0000000E
0000000F
00000010
```

**Comment by KMFDManic** [comment]
@mahoneyt944 thanks, man.  I will do a revision pull request sometime this week, to account for the volume control and anything else.  Thanks, and get better soon!

**Pull request merged**
