### PR TITLE
Artwork overlay improvements (update)

### PR DESCRIPTION
**Pull request by jamiecurmi**
Updates to artwork.h and artwork.c that should fix the compile errors on Android platforms.

### CODE REVIEW

**Comment by mahoneyt944** [comment]
@jamiecurmi looks like it built correctly now

**Comment by jamiecurmi** [comment]
@mahoneyt944, excellent. Hoping people like the changes. If/when you guys decide to release a new version on the world with updated docs, will gladly help out to explain changes where I'm needed.

**Comment by mahoneyt944** [comment]
@jamiecurmi I don't work with the documentation so much but @markwkidd might be able to help you with that.

**Comment by markwkidd** [comment]
@jamiecurmi thankfully working with libretro docs is as easy as working with github and the simple Markdown formatting syntax. the docs for this core are generated from this file: https://github.com/libretro/docs/blob/master/docs/library/mame2003_plus.md

Whenever you are ready to make updates we can talk through it here or over in that repo, just tag me. Thank you for your contribution!!

**Pull request merged**
