### PR TITLE
port Nayslayers video code

### PR DESCRIPTION
**Pull request by grant2258**
Im putting this pull req in pending @nayslayer  permission as he done the code

### CODE REVIEW

**Comment by nayslayer** [comment]
I'm fine with it - I've tested it today and found no problems. If you're talking copyrights, feel free to use my work anytime, anywhere :)

**Comment by grant2258** [comment]
thanks appreciated my good man

**Comment by grant2258** [comment]
a lot more than outrunners 👍

**Comment by nayslayer** [comment]
> So is this just to fix Outrunners so only one screen will be displayed ? Are there any more games that this fixes that use a seperate monitor for each player ? I think 'Backfire' is one.

This corruption in Outrunners is a very specific one where the monitor output looks like it's straight out of a shredder. This issues limited to multi-monitor games - I know that `sonicp` was affected too. I believe the mame version this core was built upon just didn't do multi monitor setups in a consistent way, so `backfire` just doesn't have an off switch for the extra monitor, though the picture looks fine.

And this was an afterthought anyway, the main issue was with games that required mirroring, those will now work, if it's any consolation.

**Comment by 2xtime** [comment]
Is there any chance of a list of roms that this commit fixes ?

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/issues/133

this was done a while ago is probably more

**Comment by wn2000** [comment]
I'm having display issues with a lot of Neo-Geo games and finally tracked it down to this commit. The screen is split into two sections with duplicate graphics, and weird purple colors. Not every Neo-Geo game has issue though. For example, Metal Slug 1/4/5 work fine, but Metal Slug 2 and 3  have problem.
I'm running in a rockchip 3328 based aarch64 Linux.

**Pull request merged**
