### PR TITLE
added control info for spacewar

### PR DESCRIPTION
**Pull request by robertvb83**
Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by robertvb83** [comment]
@markwkidd there went something wrong here. Only button 1 is recognized in the controls menu.

**Comment by robertvb83** [comment]
@markwkidd could it be because of button1 and 3 are defined before `PORT_START /* inputs */`
definitions and you are counting buttons only after inputs definition?
smartselect_20190122-153157_chrome

**Comment by grant2258** [comment]
thats because its a dip switch and not an input.

**Comment by robertvb83** [comment]
Hmm ok its not so easy to understand for me because buttons 1 and 3 are inputs for each player and not dip switches... we need buttons 1 2 and 3 to control the game!

**Comment by markwkidd** [comment]
This might be a good game to have a CFG file available for download as part of the collection here: https://www.bountysource.com/issues/68042280-multiple-gamepads-mapped-to-one-retropad-and-one-gamepad-to-multiple-retropads

**Comment by grant2258** [comment]
ill look a little later needless to say use legacy mapping on and the tab menu for now this works properly it the ra side that needs fixed.

**Comment by grant2258** [comment]
the fingers basically need to use the mame structures and the joystick stuctures and it should work fine. Right now its using a static joypad definition

**Pull request merged**
