### PR TITLE
compile fix

### PR DESCRIPTION
**Pull request by MistyDreams**
@mahoneyt944 though we where relaxed on the c99 stuff are // comments still ok?

### CODE REVIEW

**Comment by arcadez2003** [comment]
Nah everything needs to be /**/ as per i got into trouble when i updated tecmosys.c a while back

**Comment by arcadez2003** [comment]
Alright im getting rid of all the // i'll send the pr's shortly

**Comment by arcadez2003** [comment]
Well either way it's all good now no harm done :)

**Comment by mahoneyt944** [comment]
After removing the c99 restrictions, // comments work but out of habit I try to use /**/ as much as possible. Technically both are fine but it's safe habit to adopt to use /**/

**Pull request merged**
