### PR TITLE
Artwork overlay improvements

### PR DESCRIPTION
**Pull request by jamiecurmi**
Hey guys. Quite a lot of changes around artwork to improve overlays on black and white games, and support switching overlays on changing between upright and cocktail mode on games that support it. Also a huge update to many of the overlays used on black and white games to be more accurate to actual machines, with links in code and wiki to sources of information.

Changes to artwork are all backward compatible, so don't break existing use of artwork, while adding new abilities such as triangle colour overlays, and the ability for the end user to change opacity used on overlays.

I've put together a wiki page with images to explain all the changes:

  https://github.com/jamiecurmi/mame2003-plus-libretro/wiki/Branch-Discussions

Please take a look, and hopefully accept my pull request.

Thanks.

Jamie
jamie@curmi.com
---

Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by arcadez2003** [comment]
@jamiecurmi An impressive amount work here, im happy to push your changes to mainline with the understanding
that if anything breaks or there are compile issues afterwards you'll be the one to sort it.

@mahoneyt944 @markwkidd 
Any input around this.?? i gotta be honest here ive never had much to do with overlays myself

**Comment by mahoneyt944** [comment]
@arcadez2003 this is going to require a good bit of testing. This is more of an overhaul than a minor improvement. Hard to say how many games will get effected with how our drivers are tangled together.

**Comment by jamiecurmi** [comment]
Hi @arcadez2003. Of course, if pushed I am happy to fix any issues. COVID-19 has given me a lot of free time (hence all these changes).

Agreed, @mahoneyt944, about testing. I've tested a lot myself, and where possible I actually have arranged so code changes are not executed if default settings are used; so for example, artwork resolution of 1 or 2 does not go through new code paths, to avoid any speed issues with new code (3 or higher) and also avoids any errors in the code. Similarly, opacity of default uses old code, and avoids new code. Intention being that existing code should generally not have any slowdowns or new bugs. But of course would love a bit more testing, as realise there are lots of changes here.

**Comment by Wilstorm** [comment]
@jamiecurmi - Is there any chance you can give Depth Charge some love? It fits right in the wheelhouse of the list of games. I think it's a fairly simple blue overlay. This looks like a beast. Did you see any performance regression? Does it integrate with Libretro or interfere with its functionality of overlays, bezels & shaders? I use quite a few bezels and shaders but I am trying to think if I used any type of overlays. I don't know but I think Gorf is just considered a bezel but it's fairly fancy. I think Space Invaders had bezel issues or clipping or something so I might be running that one in AdvMAME.

**Comment by jamiecurmi** [comment]
> @jamiecurmi - Is there any chance you can give Depth Charge some love? It fits right in the wheelhouse of the list of games. I think it's a fairly simple blue overlay.

That should be easy enough @Wilstorm. I think if I can get the group to accept my changes, I'll make another branch with your requested change (and anything else I missed) and push it. Will try and find some actual screenshots of a real machine like I did with the others if I can, to make it as authentic as possible.

> This looks like a beast. Did you see any performance regression?

No. Most of the work was already done by others, I just cleaned up some things and added support for triangles and upright/cocktail mode overlays. The rest was just going through videos of arcade machines and trying to duplicate overlays as best as possible. I tried hard to make sure it didn't go into any new functionality if it didn't need it, to avoid the default showing any changes or performance issues. The only performance issue is if you try and use an artwork resolution greater than 2 (which is a new feature). My raspberry pi 3 drops the frame rate if you go above 2, a 4 might be able to do 3 or 4 perhaps. My Mac can handle > 2 easy enough in testing.

> Does it integrate with Libretro or interfere with its functionality of overlays, bezels & shaders? I use quite a few bezels and shaders but I am trying to think if I used any type of overlays.

It doesn't interfere in any way. If you have included your own .art files, with overlays, then you'd have to either turn off the colour overlay in the art file, or set opacity to 0 (new setting) to continue to use your own. That's really the only difference here.

> I don't know but I think Gorf is just considered a bezel but it's fairly fancy. I think Space Invaders had bezel issues or clipping or something so I might be running that one in AdvMAME.

I've been working on a vertical arcade setup (so a rotated monitor), and have bezels for Gorf and Space Invaders. These work in tandem with the in built overlay on Space Invaders, so you get the colour, but can also get the backgrounds. Gorf doesn't use colour overlays, but it does have bezels. I made some specifically for vertical layout on my monitor. Space Invaders should be fine on MAME2003-plus; I've seen no clipping issues. It may just be your bezel dimensions are set up wrong? Art files can be tricky to get right depending on your monitor dimensions and the artwork you are trying to put on them.

**Comment by Wilstorm** [comment]
@jamiecurmi - It sounds pretty slick, on paper at least...it sounds great! ;) There a few classics that would definitely show an improvement I would be grateful to see.

When I said bezel I meant overlay. I don't like their terminology. Yes I use many many overlays but I don't think I have any of the ones that are the cellophane type like Depth Charge, Circus, Maze, Gunfight, etc. You have a lot of them. Are those just transparent overlays or backdrop artwork? Those are definitely what I would be interested in. 

If it's just the .art files from backdrops I have a few custom ones. One for Omega Race and Space Invaders in addition to the 40+ default artwork/backdrop that go under the BIOS/artwork folder.

I have about 100 overlays (bezel style) I would have to go into and tweak (set the opacity to 0) as most are set to 0.500000 if it refers to those.

Here's my confusion. I have .art files with my artwork/backdrops but the overlays (bezel-style) only have an opacity setting in the zip file named like this (i.e. - invaders.zip.cfg) located with the ROM. It's what Libretro uses. Then the .png and .cfg files are located in another folder to complete the setup.

Yes the SI overlay I'm using needs tweaked as to not cover part of the play area. It's not the positioning but the actual overlay. 

I had to read that backdrop doc several times. Finally after I figured out what they were doing with positioning I created an Excel spreadsheet that does all the calculations. You basically plug the backdrop x,y and the game area x.y and it calculates the rest so you basically end up with this -0.16482,0,1.16482,1 as you know how all that works already.

Kind off topic and it's been a while when I compared mame2003-pluss' vector settings to AdvMAME. They both look great but AdvMAME has a slight edge as shown below in the screenshot.

Omega Race vector settings (mame2003-plus vs. AdvMAME):
AdvMAME-Plus

Also UDb23 built a great "cockpit" backdrop for Omega Race shown below. He also created a star background that looks sharp too. I tweaked the brightness to my liking on my own TV:

omegrace

Anyway I look forward to seeing how it all turns out.

**Comment by Wilstorm** [comment]
In addition to Depth Charge that uses the cellophane overlay I would also add "Lazer Command" to the list which is in the same category of those cellophane type games. It's a nice green and gold-ish color. Only two on that one, fairly straight forward.

The vector overlays would be nice too...I had to set the Star Castle backdrop really low or the ship vector lines just got lost when playing.

**Comment by Wilstorm** [comment]
One last question does your Gorf artwork fully work as in the ranks and what not light up?

**Comment by jamiecurmi** [comment]
> One last question does your Gorf artwork fully work as in the ranks and what not light up?

Yep. Probably not of use to you (or anyone really) unless they are doing a purely vertical arcade project, but here are screenshot of some of my vertical artwork. I've rearranged art to try and make the game use as much space as possible (full vertical height if possible) on the vertical monitor (at correct aspect ratio for the game) but include bezels that are either required (such as Gorf ranks, or scoring in Buck Rogers) and trying to stay true to the original design of the bezels. Where a game is horizontal, there is plenty of room above and below to add important bezels. Where it is vertical, there is sometimes a thin area on left or right that works.

gorf-201215-130934&nbsp;&nbsp;&nbsp;barrier-201215-125357
sspeedr-201215-125235&nbsp;&nbsp;buckrog-201215-125458
sitv-201215-130408&nbsp;&nbsp;redbaron-201215-130216
invaddlx-201215-125601&nbsp;&nbsp;invaders-201215-125639
llander-201215-125754&nbsp;&nbsp;canyon-201215-125301
spyhunt-201215-130322&nbsp;&nbsp;missile-201215-130038

> When I said bezel I meant overlay. I don't like their terminology. Yes I use many many overlays but I don't think I have any of the ones that are the cellophane type like Depth Charge, Circus, Maze, Gunfight, etc. You have a lot of them. Are those just transparent overlays or backdrop artwork? Those are definitely what I would be interested in.

Yes, they are transparent overlays, not backdrops. The backdrops are the backgrounds you have under the artwork. The overlay is generally the colour on top.

So what I am saying is, with the changes I've pushed, your art files remain the same, except if you've used a colour overlay in your art file. If you haven't, and it sounds like generally you (or most people) haven't, then everything is good. So you would be fine. Take my Space Invaders examples above - they have a backdrop. The colour of the graphics are in the code, so my art file just puts the image on the background.

**Comment by jamiecurmi** [comment]
> In addition to Depth Charge that uses the cellophane overlay I would also add "Lazer Command" to the list which is in the same category of those cellophane type games. It's a nice green and gold-ish color. Only two on that one, fairly straight forward.
> 
> The vector overlays would be nice too...I had to set the Star Castle backdrop really low or the ship vector lines just got lost when playing.

@Wilstorm, I'm pretty sure this is already done (in code) by someone else. I just ran it and got this screenshot. I have done no work on that to ensure it is correct compared to a real machine though. Is that the one you meant?

lazercmd-201215-124111

**Comment by mahoneyt944** [comment]
@jamiecurmi merged this. Thanks and good luck.

**Comment by mahoneyt944** [comment]
@jamiecurmi looks like there are some issues to workout, build failures. https://git.libretro.com/libretro/mame2003-plus-libretro/-/pipelines/5501

**Comment by jamiecurmi** [comment]
> @jamiecurmi looks like there are some issues to workout, build failures. https://git.libretro.com/libretro/mame2003-plus-libretro/-/pipelines/5501

Damn. Sorry. Looks like Android's compiler is a bit stricter (or the Makefile has different settings that let this pass on RPI and Linux). I'll try to find a solution as soon as I can.

**Comment by mahoneyt944** [comment]
@jamiecurmi the log shows that there are redefinition issues. Also, we don't typically declare variables within the loop header either to maintain compatibility with old compilers.
```
for (int c = 0; c < gamescale; c++)

vs

int c;
for (c = 0; c < gamescale; c++)
```

**Comment by jamiecurmi** [comment]
@mahoneyt944, is there a way I can run these tests on all architectures before pushing to you guys?

**Comment by mahoneyt944** [comment]
Create a new pull request, I'll merge it. Right now libretro is undergoing major reconstruction/ upgrades to their infrastructure so things are limited right now. Later we will be adding the rest of the platforms to our CI check in the pipeline which will identify build issues faster.

**Comment by jamiecurmi** [comment]
@mahoneyt944, pull request done. Hopefully this does the trick. With holidays coming up for me from Friday I'll work on a few other minor things for a future pull request (and some of the requests in the comments below). Let's hope this builds, otherwise I'm retiring. 😀

**Comment by Wilstorm** [comment]
@jamiecurmi - Ok, that makes sense. It seems most of the focus is on those cellophane overlays. I look forward to trying out these new changes. I have more questions but I'll just do my own testing once everything is committed. 

For the games I do it slightly different. I basically just use a HD monitor and for vertical games I fill the screen vertically (1080) and then to keep the 3:4 aspect ratio 810 horizontally or in the case of horizontal games it would be 1080 again vertically but to keep the 4:3 aspect ratio it would be 1440. So a majority of the games are 810x1080 or 1440x1080. The (bezel) overlays are then designed for those pixel dimensions in mind.

Games such as Gorf work out well because you can keep the correct aspect ratio but also the bezel artwork is still original also (plenty of space on the sides). These games on a large flat screen TV's are so huge I'm ok with running vertical games in horizontal mode. The game is still 32 inches vertically or whatever (basically huge but still maintaining the aspect ratio) if that makes sense. I get it if you're using an original arcade monitor though.

Yes Lazer Command looks great! I also saw "Datsun 280 ZZZAP" minus the car overlay. I remember it as Atari's Night Driver. 

Any chance you are going to make some of those Space Invaders backdrops above available? They are looking pretty sharp! :)

**Comment by jamiecurmi** [comment]
@Wilstorm, actually Lazer Command appears to be reversed, so actually should be corrected based on this source: https://flyers.arcade-museum.com/?page=flyer&db=videodb&id=1752&image=1

Colours are a little harder to work out if they are correct. They look more muted in the photo, but it is probably more the photo. Usually these overlays tended to be very simple bright colours.

The space invaders backgrounds I have have been cut to make them vertical, while trying to position as in old arcade machines. You probably really want the full backgrounds, which I have somewhere. I'll see what I can find.

**Comment by Wilstorm** [comment]
@jamiecurmi - So the barriers should be "black bricks" and not solid colored, nice catch! Actually it's more defined that way and looks better to me. 

The color is more muted in the flyer, maybe messing with Photoshop color saturation. I don't know how you find the true colors. I've grown so used to the florescent green and gold but if there's a color correction to be had that's great too. It's a simple game that requires two players. Tank, shoot! :)

I have the one standard SI backdrop but you have the "city" one that's a nice look too. I like to switch them up once in a while, it kind of makes the game fresh.

**Pull request merged**
