### PR TITLE
add aquario no sound atm (arcadez wip) 

### PR DESCRIPTION
**Pull request by grant2258**
The sound still needs fixed other wise its working

Screenshot from 2024-01-21 18-26-41

### CODE REVIEW

**Comment by grant2258** [comment]
@arcadez2003 this seems to affe
Screenshot from 2024-01-21 18-36-14
ct the shadow in moon walker for some reason

**Comment by mahoneyt944** [comment]
Probably the machine driver change, try making an isolated machine driver for vdp only

**Comment by grant2258** [comment]
doubtful its the machine driver change only change there was the pallet length. Most likely the vdp changes. Ill leave it as is arcadez can take a look ill revisit this another way at the weekend if no progress is made :).

**Comment by grant2258** [comment]
@arcadez2003 thats it done the code in this core driver is very picky about the palette size being changed I never seen and errors either after changing it . The sounds fixed moonwalker is fine. This is probably as good as your going to get with the old code unless someone updates it but its perfectly playable if you can live with a few gfx glitches.

**Comment by arcadez2003** [comment]
Ok Let's merge it then the only games affected here are system18 and segac2 due the video changes
we can always look out for any bug reports concerning those type games down the road.

**Pull request merged**
