### PR TITLE
set classic input layout as default

### PR DESCRIPTION
**Pull request by markwkidd**
This is hopefully the final chapter in my education about which control layout should be default. No layouts have changed, but now the `Classic Gamepad` is the default.

### CODE REVIEW

**Comment by grant2258** [comment]
let me know when your done mark looks like ill need to redo my changes will be conflicts now

**Comment by markwkidd** [comment]
oh. sorry about that. you did mention that you were working on updates. I'll be glad to help resolve any conflicts with your code.

I do think I'm done with this. I've done only a little bit of testing but everything seems right. And it was only rearranging existing code so I think this is OK to move on with.

**Comment by grant2258** [comment]
no isint a big deal can copy and paste will just start again when your done is easier that way

**Comment by markwkidd** [comment]
Cool. Unless there is a mistake, I'm done with commits for the immediate future :)

**Comment by grant2258** [comment]
the offsets are right for what what you pick in controls now mark.  ie to get 8 button map you need to pick fighstick

**Comment by markwkidd** [comment]
Dang it. I don't see anything in the source that looks messed up. At least there is already logging in place from when I implemented this originally I will start testing within the next couple of hours.

**Comment by markwkidd** [comment]
I commited this incomplete change right before a very busy couple of days. Thanks for looking into this at the next level, it shows how six months is already enough for me to have forgotten parts of the input code I wrote. I'll refactor that part and push a fix now.

**Comment by markwkidd** [comment]
Next I'm about to port some changes back and forth between this makefile and mame2003 makefile to get them closer in sync. I guess I feel like playing with fire this week. 💣

**Comment by markwkidd** [comment]
Needs to be done though. They have have both had improvements separately...

**Pull request merged**
