### PR TITLE
Soundcore fix

### PR DESCRIPTION
**Pull request by grant2258**
@mahoneyt944 thats it fixed and hamaways missing sound as well technically you dont even need this update just fix the data range on the core update you done earlier.
It will have bugs compared to this one though. I was a ten minute fix to be honest so not really caring what you do with it.

### CODE REVIEW

**Comment by mahoneyt944** [comment]
Do we need the clock change on system18 too or no?

**Comment by mahoneyt944** [comment]
I only see the interface in `src/machine/system16_machine.c` is there another hiding? Or they all using that one?

**Comment by grant2258** [comment]
Well to be honest you would need to check with mame current if they are all using the same they are on this core though

**Comment by mahoneyt944** [comment]
Hmm seems like it's only connected to sys18 and not system16 so maybe it's not that much of an issue. Just use the sys18 clock I guess.

**Pull request merged**
