### PR TITLE
add core option to adjust analog deadzone

### PR DESCRIPTION
**Pull request by rsn8887**
Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by grant2258** [comment]
this isint the right way to do it and it isint the rithe variable. im working on the input at the moment will get round to this if its needed 20 isint too much. I dont thing we need a million core options this can be done through mame itself in the menus is its really needed.

**Comment by rsn8887** [comment]
Huh? That is the one I changed, see here:
https://github.com/libretro/mame2003-plus-libretro/blob/25380df0a63ab06d5938234f1fe4f4fc52375cca/src/mame2003/mame2003.c#L1896

I changed the 20 to options.deadzone.

I changed the other one, too, because, currently, you are applying deadzones twice: You apply trigger_deadzone inside convert_analog_scale. Then, afterwards, you apply deadzone again. That's why I changed that.

**Comment by grant2258** [comment]
let me do these updates i need to do real quick need to some tests then upload the first stage of pull request for the input.

**Comment by rsn8887** [comment]
ok sounds good, just wanted to help...

**Comment by grant2258** [comment]
its is helpful  I will add it just dont want a merge nightmare when I do this pull req im fixing the the cfg file format so it works with mame078 and 2003 again as well as a few other needed updates. Then ill add this. The other check isint really a dead zone it just adds some pressure for a digital press on analog to register

**Comment by rsn8887** [comment]
BTW something I noticed looking at this: For joystick rescaling, it can really help a lot to multiply first, then divide, otherwise a lot of precision is lost. 

E.g. `(a * b) / c` is MUCH more accurate than `(a / c) * b` when using integers.

**Comment by markwkidd** [comment]
Merged, thank you both!

**Comment by grant2258** [comment]
ill check the deadzones out im getting now with these changes as well

**Comment by grant2258** [comment]
src/mame2003/mame2003.c:26:19: error: expected identifier before numeric constant
 #define deadzone  1.28 * 15
                   ^~~~
src/mame2003/mame2003.c:545:21: note: in expansion of macro 'deadzone'
             options.deadzone = atoi(var.value);
                     ^~~~~~~~
src/mame2003/mame2003.c: In function 'convert_analog_scale':
src/mame2003/mame2003.c:26:19: error: expected identifier before numeric constant
 #define deadzone  1.28 * 15

**Comment by grant2258** [comment]
ill fix this in a sec i thought this would happen just doing a clean compile first then ill put a req in to fix it that variable name needs changed anyway

**Comment by grant2258** [comment]
i just tested this im finding the analog is very jerky now its no gradual like it was before

**Comment by rsn8887** [comment]
I think mine with "deadzone = 20" is the same as yours!

**Pull request merged**
