### PR TITLE
Convert line endings to Unix LF

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR fixes the line endings for the CRLF file `jollyjgr.c` [uploaded in July](https://github.com/libretro/mame2003-plus-libretro/commit/66a79c2e4dc20a0d8885b3a08eb2ca02b26fd309#diff-58ffcda036dd54dde372b095bafb61e89c34d10620849608d92442d90b2b8a7b).

The repo contains a `.gitattributes` file including the following contents:

```
# Declare files that will always have LF Unix-style line endings on checkout.
*.c text eol=lf
*.h text eol=lf
*.in text eol=lf
```

Which means, because the CRLF file is always checked out as LF, there is always "dirtiness" in git:

```
$ git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/drivers/jollyjgr.c

no changes added to commit (use "git add" and/or "git commit -a")
```

No amount of hard-resetting or rebasing can fix this. When trying to build with our Python-based build system, I get the error:

```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git fetch -v --tags --prune --prune-tags origin
```

Applying this PR directly fixes the problem.

No changes were made the file. I simply added and committed.

## How has this been tested?

With the PR applied, I can perform git operations on the repo without a dirty file error.

## Disclaimer

Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by grant2258** [comment]
Problem is these settings have different behaviours on linux and windows as far as I can remember

**Comment by garbear** [comment]
@grant2258 I did `git add --renormalize .` and it appears to result in the same commit as this PR

**Comment by grant2258** [comment]
Yes this pr is fine if it happens again that how you can fix it without too much fuss on your end if you encounter it again

**Comment by garbear** [comment]
cool, so good to go?

**Comment by grant2258** [comment]
I'd say so would just need to wait fir one of the maintainers to ok it.

**Pull request merged**
