### PR TITLE
Dont merge Attempt to fix Asura Buster sounds repeating Prelim

### PR DESCRIPTION
**Pull request by arcadez2003**
Thank you wanting to make a contribution to this project!

Please note that by contributing code or other intellectual to this project you are allowing the project to make unlimited use of your contribution. As with the rest of the project, new contributions will be made available freely under the classic MAME Non-Commercial License.

**This license can be viewed at https://raw.githubusercontent.com/libretro/mame2003-plus-libretro/master/LICENSE.md**.

### CODE REVIEW

**Comment by mahoneyt944** [comment]
Can't have a static type in a struct, so the commit above fixes that. Still being used before declaration though. I need to look at it more.

**Comment by arcadez2003** [comment]
Yeah i wasn't sure whether to add it within the struct or keep it outside as per FBN but our version of that sound
core is quite different

**Comment by mahoneyt944** [comment]
Moving it outside let's it compile, but it still has the repeated sound effects so it doesn't seem to be working as intended.

**Comment by arcadez2003** [comment]
Ok thanks for the headsup i'll double check the code to see if i missed or incorrectly setup something i'll also need 
to ask dink if other fixes are required.

**Comment by arcadez2003** [comment]
Right i've double the code noticed a couple of lines they disabled in FBN due to breakage so i've reemed em 
out here also, apart from that everything looks present and correct so it'll be one of three things......

A) This fix is not for the issue im trying to sort
B) This code wont work in our ole soundcore
C) I've setup the reset chip commands wrongly

**Comment by mahoneyt944** [comment]
> C) I've setup the reset chip commands wrongly so they're not flipping on and off correctly

I'm leaning towards this. Ra wants to keep crashing on me when I test.

**Comment by grant2258** [comment]
Not sure how your compiling this @mahoneyt944 

```
rc/sound/ymf278b.c: In function ‘ymf278b_irq_check’:
src/sound/ymf278b.c:316:66: error: ‘ymf278b_chip_in_reset’ undeclared (first use in this function)
  316 |         if(chip->irq_line != prev_line && chip->irq_callback && !ymf278b_chip_in_reset)
      |                                                                  ^~~~~~~~~~~~~~~~~~~~~
src/sound/ymf278b.c:316:66: note: each undeclared identifier is reported only once for each function it appears in
src/sound/ymf278b.c: In function ‘ymf278b_A_w’:
src/sound/ymf278b.c:376:38: error: ‘ymf278b_chip_in_reset’ undeclared (first use in this function); did you mean ‘ymf278b_timer_b_reset’?
  376 |                                 if (!ymf278b_chip_in_reset)
      |                                      ^~~~~~~~~~~~~~~~~~~~~
      |                                      ymf278b_timer_b_reset
src/sound/ymf278b.c: In function ‘ymf278b_init’:
src/sound/ymf278b.c:642:9: error: ‘ymf278b_chip_in_reset’ undeclared (first use in this function); did you mean ‘ymf278b_timer_b_reset’?
  642 |         ymf278b_chip_in_reset = 1;
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         ymf278b_timer_b_reset
src/sound/ymf278b.c: In function ‘YMF278B_sh_start’:
src/sound/ymf278b.c:695:9: error: ‘ymf278b_chip_in_reset’ undeclared (first use in this function); did you mean ‘ymf278b_timer_b_reset’?
  695 |         ymf278b_chip_in_reset = 0;
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         ymf278b_timer_b_reset
make: *** [Makefile:909: src/sound/ymf278b.o] Error 1
```
is declare in a structure ant its attempted to be accessed as a global variable.

**Comment by grant2258** [comment]
I changed all they mf278b_chip_in_reset to either chip.ymf278b_chip_in_reset  or   chip->ymf278b_chip_in_reset  depending how the chip is set and it seems to run fine no crashing like @mahoneyt944 is getting some samples seem to play twice not sure if thats normal or not.

**Comment by mahoneyt944** [comment]
> Not sure how your compiling this @mahoneyt944
> 
> ```
> rc/sound/ymf278b.c: In function ‘ymf278b_irq_check’:
> src/sound/ymf278b.c:316:66: error: ‘ymf278b_chip_in_reset’ undeclared (first use in this function)
>   316 |         if(chip->irq_line != prev_line && chip->irq_callback && !ymf278b_chip_in_reset)
>       |                                                                  ^~~~~~~~~~~~~~~~~~~~~
> src/sound/ymf278b.c:316:66: note: each undeclared identifier is reported only once for each function it appears in
> src/sound/ymf278b.c: In function ‘ymf278b_A_w’:
> src/sound/ymf278b.c:376:38: error: ‘ymf278b_chip_in_reset’ undeclared (first use in this function); did you mean ‘ymf278b_timer_b_reset’?
>   376 |                                 if (!ymf278b_chip_in_reset)
>       |                                      ^~~~~~~~~~~~~~~~~~~~~
>       |                                      ymf278b_timer_b_reset
> src/sound/ymf278b.c: In function ‘ymf278b_init’:
> src/sound/ymf278b.c:642:9: error: ‘ymf278b_chip_in_reset’ undeclared (first use in this function); did you mean ‘ymf278b_timer_b_reset’?
>   642 |         ymf278b_chip_in_reset = 1;
>       |         ^~~~~~~~~~~~~~~~~~~~~
>       |         ymf278b_timer_b_reset
> src/sound/ymf278b.c: In function ‘YMF278B_sh_start’:
> src/sound/ymf278b.c:695:9: error: ‘ymf278b_chip_in_reset’ undeclared (first use in this function); did you mean ‘ymf278b_timer_b_reset’?
>   695 |         ymf278b_chip_in_reset = 0;
>       |         ^~~~~~~~~~~~~~~~~~~~~
>       |         ymf278b_timer_b_reset
> make: *** [Makefile:909: src/sound/ymf278b.o] Error 1
> ```
> 
> is declare in a structure ant its attempted to be accessed as a global variable.

I moved it out of the struct to get it to compile. Still getting the double sounds though.

**Comment by grant2258** [comment]
@arcadez2003 aside from the chip memory variables needing changed to the structure. Which is nothing major  the ymf278b_chip_in_reset is set to 1 in init then memset to zero and set to zero again so its never set fwiw.

**Comment by arcadez2003** [comment]
@grant2258 Yeah i just followed along with FBN as a rough guide as per how to set the chip_in_reset calls
hence i asked both of ya's for some advice as to how to tweak em for use in this core as our version of the
sound core is quite different...

Im still not 100% as to where to place em and how to set em up TBH.

The MAME fix for this looks like a nightmare to backport so i was hoping dinks version would do the job.

**Comment by grant2258** [comment]
apologies mr @arcadez2003 I never realized there was an issue as well as pull request. It might be doable the only problem is  that im not in a position t o test all the driver that could be effected by any changes. I will only touch this sound update on the basis if it breaks anything its get reverted. I still have some thing to finish up for @KMFDManic this weekend. xmen6 player and something else ill need to look up where i posted it haha.

**Comment by mahoneyt944** [comment]
> just followed along with FBN as a rough guide

This seems like a plausible solution. If indeed that fixed the issue in fbneo. Maybe you could remove the code in fbneo and see if fbneo starts getting repeated sounds.

**Comment by grant2258** [comment]
@arcadez2003 ive got you patch with variables fix will look more at the weekend managed to get xmen and avengers done. I thats the only programming things I have too do. Just keep in mind any bugs pop up revert it if we get it working that is.

**Comment by arcadez2003** [comment]
@grant2258 the Sh2 speedup is for some of the Kaneko Supernova games but i suppose some others using the
CPU would benefit also, and thanks for taking a look at the soundcore i'll be interested to see what youve come
up with.

**Comment by grant2258** [comment]
I will get to this at some point and see if we can do anything about it m8

**Comment by arcadez2003** [comment]
Yeah im two minds over this a small fix in the soundcore is one thing but big changes which could break the
sound in many others quite another, maybe best we leave this alone for now

**Pull request closed without merging**
