### PR TITLE
do not pull Bigsegaupdate 

### PR DESCRIPTION
**Pull request by grant2258**
@arcadez done the updates all i done was added the ost in moonwalker and outrun. This is your core so its your call if you want to run with it. Tested outrun and moonwalker, sharrier, golden ax, shinobi all seems good. 

I would prefer if we got testers to try this out before going forward to be honest. Ill test more when i get the time.

What did i have to do to add this nothing it just worked the problems what the things we fixed along the road that was wrong with the core!

### CODE REVIEW

**Comment by grant2258** [comment]
i need to add two games to driver i for the life of me cant remember what two they where

**Comment by grant2258** [comment]
couldnt add the new dat was causing conflicts probably because the file isint tracked

**Comment by arcadez** [comment]
Yeah i agree we could do with some testers i never got that far in the process :) there seems to be
a couple of nice graphical improvements that come with this update for Heavyweight Champ
and Shadow Dancer plus Tough Turf will now have full on sound although i must revisit trying
to fix the bad sprites.

**Comment by grant2258** [comment]
there is a problem with after burner atm going to tidy this code up and do a cleaner pull

**Comment by grant2258** [comment]
libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 9994, but only 8208 allocated.
[libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 9995, but only 8208 allocated.
[libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 9996, but only 8208 allocated.
[libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 9997, but only 8208 allocated.
[libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 9998, but only 8208 allocated.
[libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 9999, but only 8208 allocated.
[libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 10024, but only 8208 allocated.
[libretro ERROR] [MAME 2003+] error: palette_set_color() called with color 10025, but only 8208 allocated.

**Comment by grant2258** [comment]
i really dont want to change this without confirming with you what it should be https://github.com/libretro/mame2003-plus-libretro/blob/d1e50f9bf791c4b56c3210dbd82985d845f24839/src/drivers/aburner.c#L897

**Comment by grant2258** [comment]
ok pr tided up as for the pallet length i changed it to 20000 for testing and it worked fine havent added the changes here yet though

**Comment by markwkidd** [comment]
oh holy moly, I thought this was an afterburner only pr but no it was part of this existing one. I'll revert

**Comment by markwkidd** [comment]
grant I apologize for making a mess of your PR here.

could you submit a new PR which I will definitely not merge prematurely?

**Comment by grant2258** [comment]
i made a mess of it all by myself lol

**Comment by markwkidd** [comment]
I still would swear  I saw a new PR in called just "fix aburner palette colors" which I thought looked harmless enough. Time to wake up over here! 👎

**Pull request merged**
