### PR TITLE
mark try pull this

### PR DESCRIPTION
**Pull request by grant2258**
I dont think this is going to work from experience since my master branch changed. Dont try fix it if it doesnt work ill redo it all

### CODE REVIEW

**Comment by grant2258** [comment]
@arcade i looked into the code more for namcos sounds what chip you decide to use is decided by what _r __w you use. 

ie pacman uses pengo.

https://github.com/libretro/mame2003-plus-libretro/blob/d08b4587a82d872809e8ed3dff69cf90c92e90f3/src/sound/namco.c#L431
https://github.com/libretro/mame2003-plus-libretro/blob/d08b4587a82d872809e8ed3dff69cf90c92e90f3/src/sound/namco.c#L526
https://github.com/libretro/mame2003-plus-libretro/blob/d08b4587a82d872809e8ed3dff69cf90c92e90f3/src/sound/namco.c#L672
https://github.com/libretro/mame2003-plus-libretro/blob/d08b4587a82d872809e8ed3dff69cf90c92e90f3/src/sound/namco.c#L754

**Comment by arcadez** [comment]
Yeah i get what your saying, although not having made the changes you have my build still
compiles, different core different build right enough

**Comment by grant2258** [comment]
geesh i can be a cabbage at times  .... so  the mystery of the namco problem is the same thing pissing the build bot off on android.

Regardless the change wont effect anything ill try revert it if you want but someone just put another define in so they didnt need to update the drivers. Sounds like something I wid dae

**Comment by grant2258** [comment]
Well mr @arcadez  i tested all the games below sound works gfx works and controls are fine.  Job well done mate all is working well was really nice playing these on the barcade with a crt overlay. Thanks for these update I for one appreciate it mate here is the list i tested below. Please be aware this is a big update youll need to do your roms.

Thing is with poleposition it has 2 pedals we only have one mapped at the moment thats something ill fix up after some input with mark but that can go in another  thread it core related.
```
battles.zip
bosco.zip
boscomd.zip
boscomdo.zip
boscoo.zip
boscoo2.zip
digdug.zip
digduga1.zip
digdugat.zip
digdugb.zip
dzigzag.zip
galaga.zip
galaga3.zip
galaga3a.zip
galaga3m.zip
galagamk.zip
galagamw.zip
galagao.zip
gallag.zip
gaplus.zip
gaplusa.zip
gatsbee.zip
grobda.zip
grobda2.zip
grobda3.zip
liblrabl.zip
mappy.zip
mappyj.zip
motos.zip
pacnchmp.zip
pacnpal.zip
pacnpal2.zip
phozon.zip
polepos.zip
polepos1.zip
polepos2.zip
poleposa.zip
poleps2a.zip
poleps2b.zip
superpac.zip
superpcm.zip
sxevious.zip
todruaga.zip
todruago.zip
topracer.zip
toypop.zip
xevios.zip
xevious.zip
xeviousa.zip
xeviousb.zip
xeviousc.zip
```

**Pull request merged**
