### PR TITLE
fix #1053 save hiscore periodically

### LINKED ISSUE #1053: Save hiscore files regularly to prevent loss of hiscore when exiting abnormally
At present, hiscore is only saved when mame exits or resets. On embedded platforms, the power of the machine is usually turned off directly, which will cause hiscore to be lost.

### PR DESCRIPTION
**Pull request by LuoZhongYao**
Save hiscore every 1000 frames to prevent hiscore from being lost when exiting abnormally

### CODE REVIEW

**Comment by mahoneyt944** [comment]
I'm a little reluctant to merge this because it effects every game using high scores and that would be an excessive amount of testing to do for anyone. The code looks ok to me though. I do wonder if this will cause any performance hits or possibly corrupted saves.... Some saves require user actions such as starting a new game to update the field properly.

Being that this is only one file being changed, it's easily to revert if we see any regressions so I'll merge it on the premise that we'll need some user  feed back.

**Comment by grant2258** [comment]
This should be optional doing this every 16.6 seconds seems excessive for people that actatually exit anyway. It's really needless unless people want it others might want an option  not to kill there hard drives because someone else turns the box off and can't be bothered exiting .

**Comment by mahoneyt944** [comment]
Could add a core option? Auto save  highscore

**Comment by mahoneyt944** [comment]
I think we could just add a option check here
https://github.com/libretro/mame2003-plus-libretro/blob/2e144d99cb57a0a4b5e5c2d715d342b457f29d89/src/hiscore.c#L339

**Comment by grant2258** [comment]
Is really up to you personally any exiting should be working anyway or fixed if there is an issue with a specific game. This is bad practice you should name it recursively save hi scores so users know its constantly saving. That way no one can complain if its on.

**Comment by mahoneyt944** [comment]
The issue was that the user is killing power to the device so no exiting code is ever called to save so this is a workaround. Agreed not ideal. Check the closed issue on this for more details, maybe you see another solution?

**Comment by mahoneyt944** [comment]
I was thinking we could have option:
save hiscore ....on exit, every 10 sec, every 30 sec, every 1 min etc

**Comment by mahoneyt944** [comment]
@grant2258 do you think this is clear enough?
https://github.com/libretro/mame2003-plus-libretro/compare/Optional

**Comment by grant2258** [comment]
Well as long as its optional it's all good. I have my raspberry pi and it has no on off issue as well but I always shut it down before powering off. The same thing would happen with a pc if they used the reset button. I think this user behaviour rather rather than anything else. You run the risk of corrupting data just unplugging on any device. The ones lacking a power button should still be shutdown via other methods.

**Comment by LuoZhongYao** [comment]
I think you can set autosave_hiscore to a value in units of frames, change HISCORE_SYNC_FILE_DELAY to autosave_hiscore, turn off autosave hiscore, you can set autosave_hiscore to INT_MAX or LONG_MAX, so you can adjust the save interval, the disadvantage is that the options are not intuitive

**Comment by mahoneyt944** [comment]
I merged a core option. I think it's clear enough default / recursively. Needs tested though.

**Pull request merged**
