### PR TITLE
gotFrame main run loop gain

### PR DESCRIPTION
**Pull request by mahoneyt944**

### CODE REVIEW

**Comment by mahoneyt944** [comment]
Copied this over manually, look good?

**Comment by mahoneyt944** [comment]
@grant2258 Copied this over manually, look good?

**Comment by grant2258** [comment]
No Its not ready to go something different on this core.

**Comment by mahoneyt944** [comment]
Seems like the API might still expect video_cb to send that Null buffer? But I'm not sure. I'd have to check.

**Comment by grant2258** [comment]
its not that I think I have it it was foo bared. Setting gotFrame to one. Just need to do a few more tests. We where rendering more than we needed too.

**Pull request closed without merging**
