### PR TITLE
Gaiapols

### PR DESCRIPTION
**Pull request by mahoneyt944**
added bootstrap, issue #753

### CODE REVIEW

**Comment by KMFDManic** [comment]
@mahoneyt944 Thanks for the ping on this.  To further enlighten you on things, the bootstrap significantly lowers memory unload (80 MB plus) hurts really bad on 256 MB of RAM!  I have been using Virtual Swap to added an additional 512 MB of RAM as a placeholder in running the Japan Variant.  With THIS commit, Virtual Swap should feasibly be rendered unnecessary, and much less likely to cause crashes as the .nvram creates, like in Monster Maulers.  Thanks for looking into this:)  

And, be sure to look at my fork of MAME 2003 Xtreme, which I have a few things I am planning on trying to work in Next Update I post.  Currently, was working with the "pull request" you will see from Grant2258, that him, and myself, and Arcadez2003 were all trying to work with...to get some of the great Seta Hunting Games and Golden Tee Golf Games implemented.  My main snag, which may be compiler related, is "Anonymous Version Tag Cannot Be Used".  If I can resolve that, then some more fun games make it!  

But, for now, really digging the boot strap!  I will be very interested in anything else you can shed light on or recommend, as well.  But, remember, Plus focuses on overall compatiblity and stability.  I try to keep Xtreme just a tad unstable enough, so that Performance and Speed can be better, optimally, on the lower spec platforms I work with!

Also, be sure to check out some of the Custom OSTs we got implemented!  They are absolutely amazing!  

https://github.com/KMFDManic/mame2003-xtreme

And, Kyland K, by the way, nice to officially make your acquaintance:)

And, @markwkidd AWESOME to see you are back!  Hope youre feeling better!!!!!

**Comment by mahoneyt944** [comment]
@KMFDManic  I'm usually pretty good at solving bugs / updating things as well as backporting.  For what I lack in this core's specifics I make up for with relentless testing, persistence, and attention to detail. I try to focus on the user experience and simplicity. As far as bootstraps go, these are very easy to implement and I don't mind going after them. I really don't play the majority of the supported titles, maybe 100 games, so if there's any titles that need bootstraps just make a issue for that title and I'll knock it out. This one should have been done long ago but I've only recently started working on this core.

**Comment by KMFDManic** [comment]
@mahoneyt944 Looking good!  The other thing I had chatted with them about hopefully doing is similar, with nvram creation.  But, with games like Terminator 2 and Revolution X, where the values are already calibrated, and people can easily play them from the get go.  I did it for some games.  What would be nice is having them automatically done, when the game is loaded.  At the following link are two nvrams I created, which immediately allow controls for either/or, with controller, without unnecessary calibration.  Since Terminator 2 expects it to be done for both Players, and Revolution X for all 3 Players, it isn't user friendly for most.  They can be forced into use.  But, automatic would be far nicer, Core wise:)  Just one of many things I have on my list to look into and try to pull off.

https://drive.google.com/drive/folders/1vxajV07ktUlPhdb15IMkYqd2OiQmBPNY

**Comment by mahoneyt944** [comment]
@KMFDManic 
I'll add the boot strap but before I do, does the term2.nv work for the other revisions , ( term2la1 and term2la2 )? It looks like they all probably need it.

**Comment by KMFDManic** [comment]
@mahoneyt944 Should work fine on both of those, as long as it points to their names.  Over time, I would like to try to work in calibrations on games that truly need them.  Some, I hard code in, others would need bootstraps. 

And, additionally, since Revolution X falls into the category of Midway Games...some of those have very low volume.  I plan on having those preset to higher volumes within the coding, itself, so the MAME Menu, Dip Switches, etc, aren't needed to be bothered with.

So many things to fix up.  But, this is great progress.  And, we got a few fixes in to help make the MAME 2003 Xtreme Compilation for other platforms, such as PC, viable, too.

Another thing we didn't quite get to, but no rush...some of the hacks that made it into HBMAME, such as "always turbo fire on" with games like 1942, would be fun to try to work in, at some point.  But, they'd have to be smartly worked in, so they don't muck with the main games, sorta like with the DK hacks.

**Comment by Wilstorm** [comment]
I think you'll have to run the games once after you rename them to the clones or you'll get a CMOS error on boot. After that they should work without needing to recalibrate and no CMOS error.

**Comment by mahoneyt944** [comment]
@Wilstorm @KMFDManic  fixed the boot straps, made separate bootstraps for term2 clones so CMOS always passes. I noticed revx fails on u76 labeled as a custom rom. Everything else works fine. Not sure what that's about but it plays through just fine.

**Comment by mahoneyt944** [comment]
@Wilstorm @KMFDManic  PR #855 This took a little while to get right. Found some small errors in bootstrap.c that were throwing me off from old commits. Fixed now.

**Comment by KMFDManic** [comment]
@mahoneyt944 awesome.  Gonna work these into Xtreme, as well.  This really opens up things in an excellent way, since many games are ones people try, see they have confusing calibration issues to account for, then give up.  This solves that dilemma:)  Aaron Giles used to have some nvrams "linked to" on his site, including tougher to do games, such as Hard Drivin'.  I may play around with that and Race Drivin' a little more, as those are probably the toughest ones to do, due to the preciseness of the driving and braking controls.  

This is the guide that DOES work, if you do it correctly.  I may retest some of the other problem games on the list, to see what else is affected by various issues detailed.  Several have been fixed in Plus, over time.  Would have been nice if those nvrams he had originally posted were still around.  But, they may have inevitably need redone, in any case.  So, I guess, not a huge deal.  Just takes a little patience to properly calibrate the driving games.

https://wiki.mamedev.org/index.php?title=FAQ:Games#Hard_Drivin.27_.2F_Race_Drivin.27

 The entire fixing up of analog controls in Plus was a result of my discussion with Grant2258 about trying to get games like Hard Drivin' actually working well:)  Definitely no rush on this one.  I will likely play around with this one more when I get caught up on a few other things.  Performance is usually pretty awful for a lot of platforms, too, for the Hard/Race Drivin' Games, which also made it not a huge hurry.  The MD Version of Hard is well done.  I also have the Arcade Version on Midway Arcade Treasures 3 for PS2, which runs nice.  

Always things to do:)  But, reasonable stuff would be more impactful for most End Users.  You won't see too many running Hard Drivin'!  But, I always had fun with games like that and Trackmania, etc!

Thanks again for all you've done with this, over the last several days!  And, also, @Wilstorm nice seeing you back again, too:)

As a final note, there were a few other things I was curious about in the past.  But, these are not very feasible, due to the differences in coding NOW and THEN.  Ones like Outfoxies on 2003 having sound (at least it works fine in 2010, albeit slow on worse platforms), Solar Assault (A 3D Gradius Game that is quite fun) works alright on MAME 2014 and on (main rom has issues, clone works).  Backporting is not always easy.  But, Arcadez2003 got many great ones added, including Night Slashers, Rohga: Armor Force, Boogie Wings, etc.  

Chat again, soon:)  Thanks again!

**Comment by mahoneyt944** [comment]
@KMFDManic I think a lot of those games get less attention just because trying to gas, brake, clutch, gear shift and steer without foot pedals is a bit much for a typical controller and never feels right. My arcade cabinet doesn't even have that many buttons which is why I stick to 2 button games or dual joystick games. Bootstraps are easy to make and I actually prefer making my of NV files because I test the crap out of the bootstrap before creating a PR for one. That way I know it done properly. For example. I played term2 and revx entirely through and testing dip options. Which is how I found that revx had bad coin settings, which I believe is still bad in current mame.

**Comment by Wilstorm** [comment]
@mahoneyt944 @KMFDManic - Thanks for the work on these guys! It's a few less nvram files I need to store in my "new image install" folder. m3plus has a lot less nvram files due to the core bootstraps but mame2003 still needs them so I keep them around.

@mahoneyt944 - A complete play through, that's dedication! ;) What did you use for controls? I find analog controls on a controller are worthless and to fast. The circle restriction on controllers makes the gun move in a diamond pattern and works exactly like a 4-way restrictor. You loose the corners.

The best way to play I found is map the d-pad to the light gun controls and then use analog to digital on the left stick works well. It's not going to get you competition scores due the stick moving to slowly from one side of the screen to the other. If it did move a little faster it would be an almost perfect experience barring the use of real light gun.

On my old revx nvram I get that same custom ROM error.

On a side note Hard Drivin' is a classic game! On the Pi 3 it's just not playable with the slow FPS that I could find. I do have the Pi 4 overclocked stable to 2100 MHz and the v3d_freq at 850. Several hours of stability testing. I would be interested if that helps the play at all for such a classic game.

**Comment by mahoneyt944** [comment]
@Wilstorm I used digital controls. It's not ideal but it's still fun

**Comment by KMFDManic** [comment]
@Wilstorm Truly sucks that Hard Drivin' is so strict and unoptimal.  It is definitely of a nice subset of games that really don't run well, including those pesky Vegas Hardware games, such as Gauntlet Dark Legacy!  Warner Bros has a goldmine they can rerelease, and really should!  Get M2 on the case, and we will have ALL of these in a nice Next Gen collection!  And, still curious how they had such an inferior version of Race Drivin' on SNES, comparatively speaking to the much much more adept Hard Drivin' on MD!

And, clearly, we probably won't see a reissue of a game like Revolution X, unless licensing hell can be accounted for!  Gotta wonder if they could ever just ReRelease Golden Eye, without the Bond License.  Yet another game that is in perpetual hell as far as a rerelease!

**Comment by mahoneyt944** [comment]
@KMFDManic 

For revx , I just need to figure out the sound setting. I was able to set it in the bootstrap but the driver doesn't actually use the setting until one of the volume buttons is touched. I have a few ideas how to quick bypass this but ideally the driver needs to check this setting before turning the sound on.

**Comment by Wilstorm** [comment]
@mahoneyt944 - Yeah I agree, it's still fun to play, even on controllers! I do have a box with sanwa sticks also. I was just being lazy using a controller even though I prefer an old school panel for a real game session. For testing a controller is ok. 

I meant I keep the nvram files for mame2003. Anytime a bootstrap is added to m3plus I delete them from the mame2003-plus/nvram folder but leave it in the mame2003/nvram folder since that core doesn't have bootstraps. Any advantage to using the bootstraps you're creating here in the sister core?

Ah that makes sense with the serial number/authentication.

@KMFDManic - You definitely check all the right boxes for golden games I would play and your OST's are phenomenal! We could have a "therapeutic" game session together anytime! ;) My better half isn't a big gamer but she's a die hard Mario Kart 64 player so we play that quite a bit. She has the edge on me as the better racer and she likes to gloat about it too because it's one of the few games that she is better than me, most of the time but not all of the time!

**Comment by markwkidd** [comment]
I added the bootstrap functionally to the plain 2003 core as well. In
general I'd guess that most nvrams that work in 2003-plus would also work
there.


Sometimes I've had luck using archive.org to pull up preserved copies of
emulation related webpages and, on a couple lucky days, even old zip file
downloads with useful material that has long been offline. That might be an
interesting place to look for these old nvrams that have been mentioned.
.

**Comment by Wilstorm** [comment]
@markwkidd - Ok, that's handy to know, just to clarify, someone would need to generate the bootstraps correct? It has the functionality but not the actual bootstrap submissions if that makes sense?

**Comment by KMFDManic** [comment]
@Wilstorm If your better half was a bigger gamer, you wouldn't be much of a gamer, at all:)  Mine games, but I have her set up on my Xbox One, with games, such as Torchlight 2, Red Dead Redemption, etc.  But, if we played the "same" games, then the controller would likely not be in my hands, as much!  I am far more Retro Oriented.  Most current game I played was Maneater on PS4!  And, for me, that is Retro, because it is essentially Jaws Unleashed Redux!  As I better adapt to the game, things get a little more insane, throughout the course of my very first playthrough on this:)

https://www.youtube.com/watch?v=Fdq0tBSQlwI&t=611s

**Comment by markwkidd** [comment]
Wilstorm I think we're on the same page. I did as much as I could towards
the end of my active contributions to unify the codebases except in the
area of new drivers in plus.

It looks at first glance like the code is there and all we need to do or
generate bootstraps/nvram. If someone wants to take that on and it isn't
working I would try to help them out even though you all are much less
rusty with this than I am ☺️

**Comment by mahoneyt944** [comment]
@Wilstorm @markwkidd  gaiapols, term2, term2la1, term2la2, and revx all have working bootstraps in mame2003-plus now. Mame2003 supports bootstraps but these newly added titles are not in mame2003 yet.

**Comment by Wilstorm** [comment]
@KMFDManic - I just watched your video, that made my day, what a hoot! I can go classic or modern, I love western's (thinking old Eastwood spaghetti westerns and The Duke, John Wayne) so Red Dead is spot on. I like the Torchlight series too. Depending on the mood I can go either way, classic or contemporary. I loved the nod to Jabberjaw from the 70s and if it was intentional Breaking the Law from Priest, early 80's, big fan here.

@markwkidd @mahoneyt944 - mame2003-pluses base code is from mame2003 which doesn't have all these nvram enhancements that Mark originally put in place and he wrote an excellent tutorial to boot for adding new ones. Many of the changes have been ported to mame2003 by Mark, Grant and Arcadez but some have not been so basically I keep them in the mame2003 folder also to avoid the boot issues. 

That way I can flip cores for testing and what not. I use the RetroPie's Arcade folder and when a game boots I hit any button and it pulls up a menu and I can pick what core I want to play a game with. It is a bit redundant so I only use it to test if something is broke/works in vanilla 2003 vs. Plus.

m3plus is my main core, the other thing I do keep both .cfg and .nvram files for is to set 3 and 4 players by default. Games like Dungeons and Dragons, Karate Blazers, etc. are defaulted to 2 players. I have a small list of those too.

**Comment by mahoneyt944** [comment]
@Wilstorm  just updated mame2003 with all the bootstrap updates from plus.

**Comment by KMFDManic** [comment]
@mahoneyt944 I will also update these to my Xtreme Fork.  Things looking better, by the day!

@Wilstorm I can help you with a build to test on Retropie, too, if you want to have another variant to work with.  I generally use Plus/Xtreme as my main two for 2003.  Plus, Street Fighter II Custom OST is absolutely amazing with Xtreme!

https://www.youtube.com/watch?v=ooURAXmKY60

**Comment by Wilstorm** [comment]
@mahoneyt944 - You're on fire... sizzlin'... any enhancements are a win-win for all that use the cores! Thanks a bunch! ;) So are all the bootstraps form plus in vanilla now? I can delete them all? Mark did quite a lot over the months. I'll have no files left in my new build folders! ;)

@KMFDManic - Every time I watch your videos I have to smile. You have such a genuine enthusiasm and love for gaming! I would definitely try a variant build on the Pi. It's pretty much all I use for Retro gaming. I bought one of those PS mini's for super cheap new in the box but we just haven't made time to try it out yet.

**Comment by KMFDManic** [comment]
@Wilstorm For now, try this build, grab the 2 files, and you should know where to put them:)

I will upload another build, if this one works out for you.  But, THIS one will be able to run the Street Fighter II Arcade Custom OST, which you can grab at:

https://drive.google.com/drive/folders/1_Orprc2nj70gxVU0k2aw9MOKAKpSeQ1u

Path for the samples should be: system/mame2003-xtreme/samples/sf2.zip here

Enjoy it!  I am playing around with other additions, and you will be able to try those out once added.  But, SFII should be a fun ride for you, in the meantime!  And, thanks for the compliments on my videos!  

Confirm once you've grabbed the build from Google Drive.  And, of course, how things work out for you!

**Comment by mahoneyt944** [comment]
@Wilstorm if it's supported in plus it's now supported in vanilla. You should check bootstrap.c for the titles you have to see if you need to keep any of the NV files you have or not.

**Comment by Wilstorm** [comment]
@KMFDManic - Thanks for sharing the links and the fun videos! I just grabbed a copy and I'm off for a few days to take care of some things but will give it a go soon.

@mahoneyt944 - Thanks a bunch also for all the updates and the tip on how to check for which bootstraps are implemented!

**Comment by KMFDManic** [comment]
@Wilstorm Thanks for being patient!  I typically work straight back to back from Friday-Saturday, into Sun AM.  Being that you are on Pi 4, I may have to adjust the compile a little to be compatible with it.  I will see what I can do and try to post another test subject for you to try out.

**Comment by Wilstorm** [comment]
@KMFDManic -  No hurry at all, this is all meant to be fun and if completion feels hurried or needed now type thing it can become a bit "stressful". Definitely take you time. I know you're platform is the mini and if this doesn't pan out that's OK too. So many games to play, so little time! A lot of times we just do things as a family on the weekends and yesterday we went kayaking for about four hours on the river, it was a lot of fun but you work your arms pretty hard, especially going upstream! 💪

**Comment by Wilstorm** [comment]
@KMFDManic -  No hurry at all, this is all meant to be fun and if completion feels hurried or needed now type thing it can become a bit "stressful". Definitely take you time. I know you're platform is the mini and if this doesn't pan out that's OK too. So many games to play, so little time! A lot of times we just do things as a family on the weekends and yesterday we went kayaking for about four hours on the river, it was a lot of fun but you work your arms pretty hard, especially going upstream! 💪

**Comment by Wilstorm** [comment]
@KMFDManic -  No hurry at all, this is all meant to be fun and if completion feels hurried or needed now type thing it can become a bit "stressful". Definitely take you time. I know you're platform is the mini and if this doesn't pan out that's OK too. So many games to play, so little time! A lot of times we just do things as a family on the weekends and yesterday we went kayaking for about four hours on the river, it was a lot of fun but you work your arms pretty hard, especially going upstream! 💪

**Comment by Wilstorm** [comment]
@KMFDManic -  No hurry at all, this is all meant to be fun and if completion feels hurried or needed now type thing it can become a bit "stressful". Definitely take you time. I know you're platform is the mini and if this doesn't pan out that's OK too. So many games to play, so little time! A lot of times we just do things as a family on the weekends and yesterday we went kayaking for about four hours on the river, it was a lot of fun but you work your arms pretty hard, especially going upstream! 💪

**Comment by Wilstorm** [comment]
@KMFDManic -  No hurry at all, this is all meant to be fun and if completion feels hurried or needed now type thing it can become a bit "stressful". Definitely take you time. I know you're platform is the mini and if this doesn't pan out that's OK too. So many games to play, so little time! A lot of times we just do things as a family on the weekends and yesterday we went kayaking for about four hours on the river, it was a lot of fun but you work your arms pretty hard, especially going upstream! 💪

**Pull request merged**
